WIP: docs: refine theme development documentation
halo-dev/docs pull request #110
Opened 2022-11-18 08:05 UTC by ruibaby

完善 Halo 2.0 主题开发的文档。

/kind documentation

Fixes https://github.com/halo-dev/docs/issues/109

TODO list:

- [x] 准备工作 - 提供从搭建 Halo 开发环境到成功应用一个新的主题的过程。
- [x] 目录结构 - 详细解释一个主题的目录构成，包括每一个目录和文件的作用。
- [x] 配置文件 - 提供 `theme.yaml` 的各个配置的解释。
- [ ] 设置选项 - 讲解如何在主题模板中使用主题定义的 `settings.yaml` 配置项。**注意：关于 settings.yaml 或许可以单独出一篇文档，因为插件也需要用到。主题和插件的文档只需要单独讲解如何使用**
- [x] 静态资源 - 讲解静态资源的引用。
- [ ] 核心路由 - 列出 Halo 核心提供的路由以及模板，其中需要包括 `文章/自定义页面/分类的自定义模板` 的讲解
- [ ] 模板变量 - 讲解系统内提供的路由对应模板中包含的变量。
- [ ] Finder APIs - 讲解数据获取 API 的使用。
- [ ] 常用代码片段 - 提供一些在主题开发中常用的代码片段，比如如何定义一个 `layout.html`，如何结构化渲染一个菜单或者文章分类等。

2022-11-21 08:53 UTC, ruibaby commented
/retitle docs: refine theme development documentation

/cc @halo-dev/sig-docs

2022-11-22 02:04 UTC, wan92hen requested changes
默认工作目录改成 `~/.halo2` 了，文档中需要进行对应的修改。
https://github.com/halo-dev/halo/pull/2728

2022-11-22 06:28 UTC, ruibaby commented
> 默认工作目录改成 `~/.halo2` 了，文档中需要进行对应的修改。 [halo-dev/halo#2728](https://github.com/halo-dev/halo/pull/2728)

Done

2022-11-22 10:39 UTC, guqing reviewed
/lgtm

2022-11-23 02:05 UTC, JohnNiang commented on docs/developer-guide/theme/template-route-mapping.md
> +一般情况下，上文提到的模板已经能够满足大部分的需求，但如果需要针对某个特定的页面进行自定义，可以通过自定义模板来实现。目前系统支持为 **文章** **独立页面** **分类归档** 设置自定义模板：
```suggestion
一般情况下，上文提到的模板已经能够满足大部分的需求，但如果需要针对某个特定的页面进行自定义，可以通过自定义模板来实现。目前系统支持为 **文章**、**独立页面**和**分类归档** 设置自定义模板：
```

2022-11-23 08:29 UTC, JohnNiang approved these changes
/approve

2022-11-23 08:37 UTC, guqing reviewed
/lgtm

2022-11-23 08:39 UTC, merged