[WIP] feat: add plugin development docs
halo-dev/docs pull request #123
Opened 2022-11-28 10:03 UTC by guqing

### What this PR does?
添加插件开发文档

### Which issue(s) this PR fixes
Fixes #113

/area docs

```release-note
None
```

2022-12-09 08:36 UTC, liuchangfitcloud commented
RouterFunction方式去创建API需要使用org.springdoc.webflux.core.fn.SpringdocRouteBuilder才会被Swagger自动发现

2023-02-06 06:14 UTC, ruibaby requested changes

2023-02-06 06:14 UTC, ruibaby commented on docs/developer-guide/plugin/prepare.md
> +- 你能成功运行 Halo 2.0.0 版本。
建议链接到：https://docs.halo.run/developer-guide/core/run

2023-02-06 06:14 UTC, ruibaby commented on docs/developer-guide/plugin/hello-world.md
> +在插件列表将能看到插件已经被正确启动，并且在左侧菜单添加了一个组，其下有一个名叫迁移的菜单。
不建议使用迁移这个名字。

2023-02-09 04:15 UTC, guqing commented
/cc @halo-dev/sig-docs

2023-02-09 08:16 UTC, ruibaby commented
@guqing 需要同时发布到 2.2.0

2023-02-14 08:21 UTC, ruibaby reviewed
/lgtm

2023-02-14 08:21 UTC, JohnNiang approved these changes
/approve

2023-02-14 08:38 UTC, ruibaby approved these changes

2023-02-14 08:40 UTC, merged