WIP: docs: 补充快速入门及用户指南
halo-dev/docs pull request #124
Opened 2022-11-28 11:30 UTC by wan92hen

```release-note
docs: 补充快速入门及用户指南
```

2022-11-30 19:54 UTC, wan92hen commented
/retitle docs: add user guide and quick start

/cc @halo-dev/sig-docs

2022-12-01 00:00 UTC, ruibaby requested changes

2022-12-01 00:00 UTC, ruibaby commented on sidebars.js
> +        "user-guide/backup-migration",
未对 2.0 进行修改，暂时去掉。

2022-12-01 00:00 UTC, ruibaby commented on sidebars.js
> +        "user-guide/faq",
```suggestion
```

未对 2.0 进行修改，暂时去掉。

2022-12-01 00:51 UTC, ruibaby reviewed
/approve

2022-12-01 00:52 UTC, guqing reviewed
/lgtm

2022-12-01 00:53 UTC, ruibaby approved these changes

2022-12-01 00:55 UTC, merged