Add a tutorial on deploying halo using docker and MySQL
halo-dev/docs pull request #13
Opened 2021-12-09 10:40 UTC by guqing

新增 `docker` + `mysql` 部署 `halo` 的文档

2021-12-09 13:17 UTC, ruibaby requested changes

2021-12-09 13:21 UTC, guqing commented on docusaurus.config.js
> +            {
好的

2021-12-16 02:13 UTC, ruibaby requested changes

2021-12-16 02:13 UTC, ruibaby commented on docs/getting-started/install/other/docker-mysql.md
> +description: Halo 使用 docker 安装 的 mysql
说法有一点问题，可以改为 `Halo 与 MySQL 在 Docker 中的部署方案`

2021-12-16 02:13 UTC, ruibaby commented on docs/getting-started/install/other/docker-mysql.md
> +- 如果你想完全通过 `Docker` 运行 `MySQL` 和 `HALO` 请参考场景一
HALO -> Halo

2021-12-16 02:13 UTC, ruibaby commented on docs/getting-started/install/other/docker-mysql.md
> +### 场景一
不建议用 `场景一` 作为标题，不方便右侧 TOC 查看。

2021-12-16 02:13 UTC, ruibaby commented on docs/getting-started/install/other/docker-mysql.md
> +1. 创建 docker 自定义桥接网络
docker -> Docker

2021-12-16 02:13 UTC, ruibaby commented on docs/getting-started/install/other/docker-mysql.md
> +mkdir -p /data/mysql
数据目录是否可以考虑放到 Halo 的工作目录？

2021-12-16 02:13 UTC, ruibaby commented on docs/getting-started/install/other/docker-mysql.md
> +注意: 请将 `my-secret-pw` 修改为自己需要的密码后再执行
建议提示密码复杂度。

2021-12-16 02:13 UTC, ruibaby commented on docs/getting-started/install/other/docker-mysql.md
> +# 1.some-mysql 为 mysql 实例的容器名称
1. 每一个命令都建议单独一个代码块，方便浏览者直接复制。注释建议不放在代码块里面。
2. 创建数据库的命令建议使用 `create database halodb character set utf8mb4 collate utf8mb4_bin`;

2021-12-16 02:13 UTC, ruibaby commented on docs/getting-started/install/other/docker-mysql.md
> +```shell
同上，不建议将注释放到代码块内。

2021-12-16 02:13 UTC, ruibaby commented on docs/getting-started/install/other/docker-mysql.md
> +```shell
同上。

2021-12-16 02:13 UTC, ruibaby commented on docs/getting-started/install/other/docker-mysql.md
> +2. 拉取配置
与下面内容空一行。

2021-12-16 02:13 UTC, ruibaby commented on docs/getting-started/install/other/docker-mysql.md
> +```shell
同上，建议单个命令单个代码块。

2021-12-17 01:13 UTC, ruibaby requested changes

2021-12-17 01:13 UTC, ruibaby commented on docs/getting-started/install/other/docker-mysql.md
> +- 如果你想完全通过 `Docker` 运行 `MySQL` 和 `Halo` 请参考小节《统一使用Docker安装》
《统一使用Docker安装》 -> 《统一使用 Docker 安装》

2021-12-19 13:35 UTC, ruibaby approved these changes
LGTM

2021-12-19 13:35 UTC, merged