docs: add documentation about compilation
halo-dev/docs pull request #138
Opened 2022-12-09 09:42 UTC by ruibaby

提供自编译可执行 JAR 和 Docker 镜像的文档。

Fixes https://github.com/halo-dev/docs/issues/114

/kind documentation

```release-note
None
```

2022-12-12 06:21 UTC, ruibaby commented
@halo-dev/sig-docs

2022-12-12 09:35 UTC, JohnNiang commented on versioned_docs/version-2.0/developer-guide/core/build.md
> +## 构建 Halo
```suggestion
## 构建 Fat Jar
```

2022-12-12 09:38 UTC, ruibaby commented on docs/developer-guide/core/build.md
> +## 构建 Halo
```suggestion
## 构建 Fat Jar
```

2022-12-13 02:13 UTC, JohnNiang requested changes

2022-12-13 02:13 UTC, JohnNiang commented on docs/developer-guide/core/build.md
> +./gradlew.bat clean build -x test -x jar
```suggestion
./gradlew.bat clean build -x check -x jar
```

2022-12-13 02:13 UTC, JohnNiang commented on docs/developer-guide/core/build.md
> +./gradlew clean build -x test -x jar
```suggestion
./gradlew clean build -x check -x jar
```

2022-12-13 08:59 UTC, JohnNiang approved these changes
/approve

2022-12-13 13:38 UTC, merged