提交pr：add(other): Nginx Proxy Manager title
halo-dev/docs pull request #141
Opened 2022-12-11 14:04 UTC by RalstonLiu

仙总，我是咕咕鸽，第一次尝试提交PR。
PR内容，准备更新Nginx Proxy Manager反向代理的内容文档，预计这周完成。

2022-12-11 14:38 UTC, ruibaby commented
/retitle docs: add documentation for use with Nginx Proxy Manager

2022-12-13 15:42 UTC, ruibaby requested changes
@RalstonLiu 我这里有一点格式的建议

2022-12-13 15:42 UTC, ruibaby commented on docs/getting-started/install/other/nginxproxymanager.md
> +## 与 Nginx Proxy Manager 配合使用
这一行可以不用添加，我们用的文档系统会自动添加。

```suggestion
```

2022-12-13 15:42 UTC, ruibaby commented on docs/getting-started/install/other/nginxproxymanager.md
> +> `「反向代理」` 部分不用进行操作，保证 Halo 服务运行无误即可。（即可以用 `http://ip: 端口号` 的形式访问博客。）
```suggestion
:::info
`「反向代理」` 部分不进行操作，保证 Halo 服务运行无误即可。
:::
```

2022-12-13 15:42 UTC, ruibaby commented on docs/getting-started/install/other/nginxproxymanager.md
> +下面我们就来介绍如何用 Nginx Proxy Manger 来配合 Halo，实现反向代理和 https 访问。
```suggestion
下面我们就来介绍如何用 Nginx Proxy Manger 来配合 Halo，实现反向代理和 HTTPS 访问。
```

2022-12-13 15:42 UTC, ruibaby commented on docs/getting-started/install/other/nginxproxymanager.md
> +> 说明：默认你的服务器已经安装了 Docker 和 Docker-compose，如果你没有安装，可以参考：[使用 Docker Compose 部署](https://docs.halo.run/getting-started/install/docker-compose) 的环境搭建部分来进行安装。
```suggestion
> 说明：默认你的服务器已经安装了 Docker 和 Docker Compose，如果你没有安装，可以参考：[使用 Docker Compose 部署](https://docs.halo.run/getting-started/install/docker-compose) 的环境搭建部分来进行安装。
```

2022-12-13 15:42 UTC, ruibaby commented on docs/getting-started/install/other/nginxproxymanager.md
> +      - '80:80'              #不建议修改端口
```suggestion
      - '80:80'              # 不建议修改端口
```

2022-12-13 15:42 UTC, ruibaby commented on docs/getting-started/install/other/nginxproxymanager.md
> +      - '443:443'            #不建议修改端口
```suggestion
      - '443:443'            # 不建议修改端口
```

2022-12-13 15:42 UTC, ruibaby commented on docs/getting-started/install/other/nginxproxymanager.md
> +> 2、遇到访问不了的情况，请再次检查在宝塔面板的防火墙和服务商的后台防火墙是否打开对应了端口。
```suggestion
:::info
1. 不知道服务器 IP，可以直接在命令行输入：curl ip.sb，会显示当前服务器的 IP。
2. 遇到访问不了的情况，请再次检查在宝塔面板的防火墙和服务商的后台防火墙是否打开对应了端口。
:::
```

2022-12-13 15:42 UTC, ruibaby commented on docs/getting-started/install/other/nginxproxymanager.md
> +至此，我们已经完成了 Nginx Proxy Manager 的搭建，之后就可以用它给我们的 Halo 或者其他 web 应用做反向代理了。
```suggestion
至此，我们已经完成了 Nginx Proxy Manager 的搭建，之后就可以用它给我们的 Halo 或者其他 Web 应用做反向代理了。
```

2022-12-13 15:42 UTC, ruibaby commented on docs/getting-started/install/other/nginxproxymanager.md
> +> 2 、如果你使用了 CloudFlare 的 DNS 服务，记得把小黄云关闭（即不开启 CDN）。
```suggestion
:::info
1. 申请证书需要你提前将域名解析到 NPM 所在的服务器的 IP 上；
2. 如果你使用的是国内的服务器，默认 `80` 和 `443` 端口是关闭的，你需要备案之后才能使用；
3. 如果你使用了 CloudFlare 的 DNS 服务，记得把小黄云关闭（即不开启 CDN）。
:::
```

2022-12-19 06:02 UTC, closed without merging

2022-12-19 06:02 UTC, RalstonLiu commented
重新提交