增加了Traefik配置文档
halo-dev/docs pull request #172
Opened 2023-01-25 19:29 UTC by scoooooott

2023-01-28 08:51 UTC, JohnNiang commented
/cc @halo-dev/sig-docs

2023-01-30 03:48 UTC, guqing commented
Hi @scoooooott，在 review 之前希望你可以通过 markdown lint 工具格式化一下文档，比如中英文之前期望有空格等

2023-02-01 15:38 UTC, scoooooott commented
> Hi @scoooooott，在 review 之前希望你可以通过 markdown lint 工具格式化一下文档，比如中英文之前期望有空格等 还有类似 Traefik 这样的名词 建议在全文都统一一下书写为首字母大写，而非时而大小时而小写 🎉🎉

👌，我会再检查一遍。请问markdown lint工具指的是文档目录中的`pnpm lint`吗？
执行后没有文件内容变更，也没有warn or error。是否我使用姿势有问题？
```
/usr/local/bin/pnpm run lint

> @halo-dev/docs@0.0.0 lint /Users/yangning/workspace/opensource/halo-docs-traefik
> markdownlint-cli2 "./docs/**/*.md" "./versioned_docs/**/*.md"

markdownlint-cli2 v0.4.0 (markdownlint v0.25.1)
Finding: ./docs/**/*.md ./versioned_docs/**/*.md
Linting: 313 file(s)
Summary: 0 error(s)

```

2023-02-02 02:58 UTC, ruibaby requested changes
感谢 @scoooooott 的贡献，这里有几点建议，有时间可以看看。

另外，目前最新的文档版本为 2.2，可能需要同时为 version-2.2 中添加，以及 docs 目录。

2023-02-02 02:58 UTC, ruibaby commented on versioned_docs/version-2.1/getting-started/install/docker-compose.md
> +你可以在下面的反向代理软件中任选一项，我们假设你已经安装好了其中一项，并对其的基本操作有一定了解。
不建议在这里添加这样的内容，你可以改为把 Traefik 的文档链接添加到下面，比如：

你可以在下面的反向代理软件中任选一项，我们假设你已经安装好了其中一项，并对其的基本操作有一定了解。如果你对它们没有任何了解，可以参考我们更为详细的反向代理文档：

- 使用 [OneinStack](../install/other/oneinstack.md)
- 使用 [Traefik](../install/other/traefik.md)

2023-02-02 02:58 UTC, ruibaby commented on versioned_docs/version-2.1/getting-started/install/other/traefik.md
> +而且能够实现Let's Encrypt证书的自动签发、验证与续期。
```suggestion
而且能够实现 Let's Encrypt 证书的自动签发、验证与续期。
```

2023-02-02 02:58 UTC, ruibaby commented on versioned_docs/version-2.1/getting-started/install/other/traefik.md
> +2. 开启Docker服务发现，监听检测docker容器声明的服务关系。[文档](https://doc.traefik.io/traefik/providers/docker/#provider-configuration)
需要注意一下中西文之间的空格，以及专有名词的写法，请参考：

```suggestion
2. 开启 Docker 服务发现，监听检测 Docker 容器声明的服务关系。[文档](https://doc.traefik.io/traefik/providers/docker/#provider-configuration)
```

你可以先使用 VS Code 的 pangu 插件来实现自动添加空格。

2023-02-02 02:58 UTC, ruibaby commented on versioned_sidebars/version-2.1-sidebars.json
> +                "getting-started/install/other/traefik",
建议按照顺序，放置在 nginxproxymanager 后面。

2023-02-02 03:06 UTC, guqing commented
> 👌，我会再检查一遍。请问markdown lint工具指的是文档目录中的`pnpm lint`吗？ 执行后没有文件内容变更，也没有warn or error。是否我使用姿势有问题？

比如使用 vscode 安装 markdown lint 插件格式化一下稳定之类

2023-02-02 06:05 UTC, scoooooott commented on versioned_docs/version-2.1/getting-started/install/other/traefik.md
> +2. 开启Docker服务发现，监听检测docker容器声明的服务关系。[文档](https://doc.traefik.io/traefik/providers/docker/#provider-configuration)
Done

2023-02-02 06:05 UTC, scoooooott commented on versioned_docs/version-2.1/getting-started/install/other/traefik.md
> +而且能够实现Let's Encrypt证书的自动签发、验证与续期。
Done.

2023-02-02 06:29 UTC, scoooooott commented on versioned_sidebars/version-2.1-sidebars.json
> +                "getting-started/install/other/traefik",
按照文档添加时间顺序确实是应该这么排列，但这里是比较建议新手直接上手Traefik的，在“getting-started/install/docker-compose#反向代理”章节，也是将Traefik作为推荐首选排列在前面的，所以sidebar中Traefik排在前面似乎比较一致？

2023-02-02 06:31 UTC, scoooooott commented
文档已经按照pangu进行了格式化，完善了一些内容，同时添加了2.2.0和2.3.0的文档内容。😊 @ruibaby

2023-02-03 13:53 UTC, ruibaby reviewed
仔细阅读了你的文档，Traefik 确实非常不错，感谢贡献。

以下是一些格式和结构的改动建议，你可以直接 `Commit suggestion`，也可以继续回复讨论。

2023-02-03 13:53 UTC, ruibaby commented on docs/getting-started/install/docker-compose.md
> +1. `networks`中引入已存在的网络`traefik` （此网络需要 [提前创建](../install/other/traefik.md#创建-traefik)）
```suggestion
1. `networks` 中引入已存在的网络 `traefik`（此网络需要 [提前创建](../install/other/traefik.md#创建-traefik)）
```

2023-02-03 13:53 UTC, ruibaby commented on versioned_docs/version-2.1/getting-started/install/docker-compose.md
> +  如果需要配置域名访问，建议先配置好反向代理以及域名解析再进行初始化。如果通过 `http://ip: 端口号` 的形式无法访问，请到服务器厂商后台将运行的端口号添加到安全组，如果服务器使用了 Linux 面板，请检查此 Linux 面板是否有还有安全组配置，需要同样将端口号添加到安全组。
```suggestion
  如果需要配置域名访问，建议先配置好反向代理以及域名解析再进行初始化。如果通过 `http://ip:端口号` 的形式无法访问，请到服务器厂商后台将运行的端口号添加到安全组，如果服务器使用了 Linux 面板，请检查此 Linux 面板是否有还有安全组配置，需要同样将端口号添加到安全组。
```

2023-02-03 13:53 UTC, ruibaby commented on docs/getting-started/install/other/traefik.md
> +2. 开启 Docker 服务发现，监听检测 docker 容器声明的服务关系。[文档](https://doc.traefik.io/traefik/providers/docker/#provider-configuration)
```suggestion
2. 开启 Docker 服务发现，监听检测 Docker 容器声明的服务关系。[文档](https://doc.traefik.io/traefik/providers/docker/#provider-configuration)
```

2023-02-03 13:53 UTC, ruibaby commented on versioned_docs/version-2.1/getting-started/install/docker-compose.md
> +3. 使用 [Nginx Proxy Manager](../install/other/nginxproxymanger.md)
```suggestion
1. 使用 [OneinStack](../install/other/oneinstack.md)
2. 使用 [Nginx Proxy Manager](../install/other/nginxproxymanger.md)
3. 使用 [Traefik](../install/other/traefik.md)
```

2023-02-03 13:53 UTC, ruibaby commented on versioned_docs/version-2.1/getting-started/install/docker-compose.md
> +1. `networks`中引入已存在的网络`traefik` （此网络需要 [提前创建](../install/other/traefik.md#创建-traefik)）
```suggestion
1. `networks` 中引入已存在的网络 `traefik` （此网络需要 [提前创建](../install/other/traefik.md#创建-traefik)）
```

2023-02-03 13:53 UTC, ruibaby commented on versioned_docs/version-2.1/getting-started/install/docker-compose.md
> +2. `services.halo.networks`中添加网络`traefik`
```suggestion
2. `services.halo.networks` 中添加网络 `traefik`
```

2023-02-03 13:53 UTC, ruibaby commented on versioned_docs/version-2.1/getting-started/install/other/traefik.md
> +2. 开启 Docker 服务发现，监听检测 docker 容器声明的服务关系。[文档](https://doc.traefik.io/traefik/providers/docker/#provider-configuration)
```suggestion
2. 开启 Docker 服务发现，监听检测 Docker 容器声明的服务关系。[文档](https://doc.traefik.io/traefik/providers/docker/#provider-configuration)
```

2023-02-03 13:53 UTC, ruibaby commented on versioned_docs/version-2.1/getting-started/install/other/traefik.md
> +1. 顶层 `networks` 中添加了外部网络`traefik`，
```suggestion
1. 顶层 `networks` 中添加了外部网络 `traefik`，
```

2023-02-03 13:53 UTC, ruibaby commented on versioned_docs/version-2.2/getting-started/install/docker-compose.md
> +  如果需要配置域名访问，建议先配置好反向代理以及域名解析再进行初始化。如果通过 `http://ip: 端口号` 的形式无法访问，请到服务器厂商后台将运行的端口号添加到安全组，如果服务器使用了 Linux 面板，请检查此 Linux 面板是否有还有安全组配置，需要同样将端口号添加到安全组。
```suggestion
  如果需要配置域名访问，建议先配置好反向代理以及域名解析再进行初始化。如果通过 `http://ip:端口号` 的形式无法访问，请到服务器厂商后台将运行的端口号添加到安全组，如果服务器使用了 Linux 面板，请检查此 Linux 面板是否有还有安全组配置，需要同样将端口号添加到安全组。
```

2023-02-03 13:53 UTC, ruibaby commented on versioned_docs/version-2.2/getting-started/install/docker-compose.md
> +3. 使用 [Nginx Proxy Manager](../install/other/nginxproxymanger.md)
```suggestion
1. 使用 [OneinStack](../install/other/oneinstack.md)
2. 使用 [Nginx Proxy Manager](../install/other/nginxproxymanger.md)
3. 使用 [Traefik](../install/other/traefik.md)
```

2023-02-03 13:53 UTC, ruibaby commented on versioned_docs/version-2.2/getting-started/install/docker-compose.md
> +1. `networks`中引入已存在的网络`traefik` （此网络需要 [提前创建](../install/other/traefik.md#创建-traefik)）
```suggestion
1. `networks` 中引入已存在的网络 `traefik` （此网络需要 [提前创建](../install/other/traefik.md#创建-traefik)）
```

2023-02-03 13:53 UTC, ruibaby commented on versioned_docs/version-2.2/getting-started/install/docker-compose.md
> +2. `services.halo.networks`中添加网络`traefik`
```suggestion
2. `services.halo.networks` 中添加网络 `traefik`
```

2023-02-03 13:53 UTC, ruibaby commented on versioned_docs/version-2.2/getting-started/install/other/traefik.md
> +2. 开启 Docker 服务发现，监听检测 docker 容器声明的服务关系。[文档](https://doc.traefik.io/traefik/providers/docker/#provider-configuration)
```suggestion
2. 开启 Docker 服务发现，监听检测 Docker 容器声明的服务关系。[文档](https://doc.traefik.io/traefik/providers/docker/#provider-configuration)
```

2023-02-03 13:53 UTC, ruibaby commented on versioned_docs/version-2.2/getting-started/install/other/traefik.md
> +1. 顶层 `networks` 中添加了外部网络`traefik`，
```suggestion
1. 顶层 `networks` 中添加了外部网络 `traefik`
```

2023-02-03 13:53 UTC, ruibaby commented on versioned_sidebars/version-2.1-sidebars.json
>                  "getting-started/install/other/nginxproxymanager"
```suggestion
                "getting-started/install/other/oneinstack",
                "getting-started/install/other/nginxproxymanager",
                "getting-started/install/other/traefik"
```

2023-02-03 13:53 UTC, ruibaby commented on versioned_sidebars/version-2.2-sidebars.json
>                  "getting-started/install/other/nginxproxymanager"
```suggestion
                "getting-started/install/other/oneinstack",
                "getting-started/install/other/nginxproxymanager",
                "getting-started/install/other/traefik"
```

2023-02-03 14:27 UTC, scoooooott commented
> 仔细阅读了你的文档，Traefik 确实非常不错，感谢贡献。
> 
> 以下是一些格式和结构的改动建议，你可以直接 `Commit suggestion`，也可以继续回复讨论。

Thanks. 已经将Commit suggestion的改动合并了，没有其他意见。鉴于Commit history有些乱，出于个人习惯，又force push了一下，请见谅。

2023-02-03 14:28 UTC, ruibaby commented
> 鉴于Commit history有些乱，出于个人习惯，又force push了一下，请见谅。

没有关系，我们合并的时候会 Squash。

2023-02-03 14:29 UTC, ruibaby approved these changes
/approve

2023-02-03 16:30 UTC, JohnNiang approved these changes
/lgtm

2023-02-03 16:32 UTC, merged