Refine docker run command
halo-dev/docs pull request #194
Opened 2023-02-27 16:27 UTC by sxbai

```release-note
None
```

2023-02-28 02:15 UTC, JohnNiang requested changes
Thank you for your first contribution!

1. 建议删除 `versioned_docs/version-2.1/.intro.md.swp` 和 `versioned_docs/version-2.2/.intro.md.swp` 文件
2. [2.3.0-SNAPSHOT](https://github.com/halo-dev/docs/blob/4fdea96f095c4b2d152813150ec63dc7acf08175/docs/getting-started/install/docker.md) 的文档也许要同步修改

2023-02-28 02:17 UTC, JohnNiang commented
/retitle Refine docker run command

2023-02-28 09:47 UTC, ruibaby approved these changes
/lgtm

2023-03-01 03:44 UTC, JohnNiang approved these changes

2023-03-01 03:44 UTC, merged