Update docker-compose.md
halo-dev/docs pull request #201
Opened 2023-03-25 07:22 UTC by wxyShine

Add docker-compose to use the existing Mysql deployment method

2023-03-26 12:14 UTC, ruibaby requested changes

2023-03-26 12:14 UTC, ruibaby commented on versioned_docs/version-2.3/getting-started/install/docker-compose.md
> +    4. 仅创建 Halo 实例（使用已有Mysql数据库）：
建议改为使用外部数据，而不只是 MySQL 数据库。

2023-03-26 12:14 UTC, ruibaby commented on versioned_docs/version-2.3/getting-started/install/docker-compose.md
> +          # MySQL 的密码，请保证与下方 MYSQL_ROOT_PASSWORD 的变量值一致。
已经不需要这个注释。

2023-03-26 12:14 UTC, ruibaby commented on versioned_docs/version-2.3/getting-started/install/docker-compose.md
> +            condition: service_healthy
不需要的 healthy check

2023-03-26 12:14 UTC, ruibaby commented on versioned_docs/version-2.3/getting-started/install/docker-compose.md
> +        ports:
如果使用 host 的 network mode，这里的端口映射似乎已经没有作用。

2023-03-27 03:01 UTC, wxyShine commented on versioned_docs/version-2.3/getting-started/install/docker-compose.md
> +          # MySQL 的密码，请保证与下方 MYSQL_ROOT_PASSWORD 的变量值一致。
如有修改端口需求，该使用那个配置参数来halo的默认端口？--server.port=8090吗

2023-03-27 03:01 UTC, wxyShine commented on versioned_docs/version-2.3/getting-started/install/docker-compose.md
> +        ports:
如有修改端口需求，该使用那个配置参数来halo的默认端口？--server.port=8090吗

2023-03-27 03:05 UTC, ruibaby commented on versioned_docs/version-2.3/getting-started/install/docker-compose.md
> +        ports:
> 

对

2023-03-27 03:08 UTC, ruibaby requested changes

2023-03-27 03:08 UTC, ruibaby commented on versioned_docs/version-2.3/getting-started/install/docker-compose.md
> +    ```
```suggestion
    ```yaml {8,21-24} title="~/halo/docker-compose.yaml"
```

2023-03-27 03:08 UTC, ruibaby commented on versioned_docs/version-2.3/getting-started/install/docker-compose.md
> +    4. 仅创建 Halo 实例（使用已有外部数据库，Mysql为例）：
```suggestion
    4. 仅创建 Halo 实例（使用已有外部数据库，MySQL 为例）：
```

2023-03-27 03:08 UTC, ruibaby commented on versioned_docs/version-2.3/getting-started/install/docker-compose.md
> +          # 修改为自己已有的MySQL配置
```suggestion
          # 修改为自己已有的 MySQL 配置
```

2023-03-27 03:08 UTC, ruibaby commented on versioned_docs/version-2.3/getting-started/install/docker-compose.md
> +          - --spring.r2dbc.url=r2dbc:pool:mysql://halodb:3306/halo
```suggestion
          - --spring.r2dbc.url=r2dbc:pool:mysql://localhost:3306/halo
```

2023-03-27 03:08 UTC, ruibaby commented on versioned_docs/version-2.3/getting-started/install/docker-compose.md
> +          - --spring.r2dbc.password=o#DwN&JSa56
```suggestion
          - --spring.r2dbc.password=
```

2023-04-07 04:03 UTC, JohnNiang requested changes
Hi @wxyShine , thanks for contribution!

可能还需要同步更改以下两个文档：

- docs/getting-started/install/docker-compose.md
- versioned_docs/version-2.4/getting-started/install/docker-compose.md

2023-04-07 06:31 UTC, JohnNiang approved these changes
/approve

2023-04-07 06:56 UTC, ruibaby approved these changes
/lgtm

2023-04-07 06:56 UTC, ruibaby commented
/hold

2023-04-07 06:57 UTC, ruibaby requested changes

2023-04-07 06:57 UTC, ruibaby commented on docs/getting-started/install/docker-compose.md
> +        image: halohub/halo:2.3.0
```suggestion
        image: halohub/halo:2.4
```

2023-04-07 06:57 UTC, ruibaby commented on versioned_docs/version-2.3/getting-started/install/docker-compose.md
> +        image: halohub/halo:2.3.0
```suggestion
        image: halohub/halo:2.3
```

2023-04-07 06:57 UTC, ruibaby commented on versioned_docs/version-2.4/getting-started/install/docker-compose.md
> +        image: halohub/halo:2.3.0
```suggestion
        image: halohub/halo:2.4
```

2023-04-07 06:58 UTC, ruibaby commented
/unhold

2023-04-07 06:58 UTC, ruibaby approved these changes

2023-04-07 06:59 UTC, JohnNiang commented
/unhold

2023-04-07 07:04 UTC, merged