refactor(插件开发): Halo 插件开发windos环境下插件绝对路径的补充
halo-dev/docs pull request #219
Opened 2023-05-23 05:36 UTC by Simple-Stark

Closes #218

2023-05-24 05:06 UTC, JohnNiang commented
/cc @halo-dev/sig-docs

2023-05-26 09:24 UTC, ruibaby requested changes
感谢贡献，这里有一些改动建议。

另外，除了 version-2.5 的文档需要改，对应的 docs 目录下的文件也需要修改。

2023-05-26 09:24 UTC, ruibaby commented on versioned_docs/version-2.5/developer-guide/plugin/runtime-mode.md
> -      - /path/to/your/plugin/plugin-starter
统一改为 `/path/to/plugin-xxx`

Windows 可以是 `C:\path\to\plugin-xxx`

2023-05-26 09:35 UTC, Simple-Stark commented
已修改

2023-05-26 13:38 UTC, ruibaby reviewed
/approve

2023-05-26 15:46 UTC, JohnNiang approved these changes
/lgtm

2023-05-26 15:48 UTC, merged