docs: add halo on podman
halo-dev/docs pull request #256
Opened 2023-09-14 17:47 UTC by wangxiaoerYah

添加使用 Podman 部署Halo的方法.

```release-note
None 
```

2023-09-15 03:24 UTC, guqing commented
/cc @halo-dev/sig-docs

2023-09-24 03:52 UTC, ruibaby commented
Hi @wangxiaoerYah ，抱歉这个 PR 没有及时 Review，我们最近在忙 2.10.x 的功能，所以没有太多时间进行验证。我将重新打开，有时间之后会验证并合并。

/reopen

2023-09-25 03:37 UTC, ruibaby requested changes

2023-09-25 03:37 UTC, ruibaby commented on docs/getting-started/install/podman.md
> +## 使用 Docker 镜像
建议提示一下为什么使用的 Docker 镜像，虽然使用者可能使用过 podman

> 我没有使用和了解过 podman，可能我说的不是很准确。

2023-09-25 03:37 UTC, ruibaby commented on docs/getting-started/install/podman.md
> +  Exec=--halo.external-url=https://xxx.com --spring.sql.init.platform=postgresql --spring.r2dbc.url=r2dbc:pool:postgresql://127.0.0.1:5432/my-db --spring.r2dbc.username=my-user --spring.r2dbc.passwor
```suggestion
  Exec=--halo.external-url=http://localhost:8090 --spring.sql.init.platform=postgresql --spring.r2dbc.url=r2dbc:pool:postgresql://127.0.0.1:5432/my-db --spring.r2dbc.username=my-user --spring.r2dbc.password=my-password --halo.cache.page.disabled=false
```

2023-09-25 03:37 UTC, ruibaby commented on docs/getting-started/install/podman.md
> +  Exec=--halo.external-url=https://xxx.com --spring.sql.init.platform=postgresql --spring.r2dbc.url=r2dbc:pool:postgresql://127.0.0.1:5432/my-db --spring.r2dbc.username=my-user --spring.r2dbc.passwor
```suggestion
  Exec=--halo.external-url=http://localhost:8090 --spring.sql.init.platform=postgresql --spring.r2dbc.url=r2dbc:pool:postgresql://127.0.0.1:5432/my-db --spring.r2dbc.username=my-user --spring.r2dbc.password=my-password --halo.cache.page.disabled=false
```

2023-09-25 03:37 UTC, ruibaby commented on versioned_docs/version-2.9/getting-started/install/podman.md
> +  Exec=--halo.external-url=https://xxx.com --spring.sql.init.platform=postgresql --spring.r2dbc.url=r2dbc:pool:postgresql://127.0.0.1:5432/my-db --spring.r2dbc.username=my-user --spring.r2dbc.passwor
```suggestion
  Exec=--halo.external-url=http://localhost:8090 --spring.sql.init.platform=postgresql --spring.r2dbc.url=r2dbc:pool:postgresql://127.0.0.1:5432/my-db --spring.r2dbc.username=my-user --spring.r2dbc.password=my-password --halo.cache.page.disabled=false
```

2023-09-25 03:37 UTC, ruibaby commented on versioned_docs/version-2.9/getting-started/install/podman.md
> +  Exec=--halo.external-url=https://xxx.com --spring.sql.init.platform=postgresql --spring.r2dbc.url=r2dbc:pool:postgresql://127.0.0.1:5432/my-db --spring.r2dbc.username=my-user --spring.r2dbc.passwor
```suggestion
  Exec=--halo.external-url=http://localhost:8090 --spring.sql.init.platform=postgresql --spring.r2dbc.url=r2dbc:pool:postgresql://127.0.0.1:5432/my-db --spring.r2dbc.username=my-user --spring.r2dbc.password=my-password --halo.cache.page.disabled=false
```

2023-09-26 15:42 UTC, JohnNiang commented on docs/getting-started/install/podman.md
> +    podman run -it -d --name halo -p 8090:8090 -v ~/.halo2:/root/.halo2 halohub/halo:2.9
这里我实测如果不手动创建 `~/.halo2` 文件夹的话，无法正常运行，请看完整日志：

```bash
podman run -it -d --name halo -p 8091:8090 -v ~/.halo2-podman:/root/.halo2 halohub/halo:2.9
Resolving "halohub/halo" using unqualified-search registries (/etc/containers/registries.conf.d/999-podman-machine.conf)
Trying to pull docker.io/halohub/halo:2.9...
Getting image source signatures
Copying blob sha256:4109c588f38accea0ad9969dea1777787659d10bee8e5d3776cd7990d41e3025
Copying blob sha256:8b5db5f6400d85199afbfde601a9e3c2051ebceb1ed9cc0fe25fe6b91e79afa9
Copying blob sha256:c4bccb525aef23b375cbcff84a9e7861c44ea0c0abcb727d4a15c43403b3bf22
Copying blob sha256:3c7073102534bbdab86f9064e784ab0da9e714df01832daf28c9a0e0879b9766
Copying blob sha256:95dea0a414858e69744d7a1b6f6cae01c0b221d826f8d5223b911fe75719ec06
Copying blob sha256:752397543fbdf2a53040baf81807321724c9cb178fa38e5ee410e4fe6032bb68
Copying blob sha256:347a915e49409c43ebd3887321283f074e15aaca81507b59d79e733f98b15039
Copying blob sha256:6ba7278f0a084752e34631b5edc3342fa6ea18669c70417a2c20910d57cb2cbc
Copying blob sha256:4f4fb700ef54461cfa02571ae0db9a0dc1e0cdb5577484a6d75e68dc38e8acc1
Copying blob sha256:db625dc104828c06d00e69ae6486ef8d6b3fed4a530d328f32439a1b56fa3be1
Copying blob sha256:576164b8c81b241d2daf5c896b5089f49c3938e77c3c22a6cde247f9c21930cf
Copying config sha256:1c8bdd3d5c293c1c2d5ddd356c931f6ff6c666e73c63058b574288bda6d55997
Writing manifest to image destination
Error: statfs /Users/johnniang/.halo2-podman: no such file or directory
```

Podman 版本信息如下：

```bash
podman version
Client:       Podman Engine
Version:      4.6.2
API Version:  4.6.2
Go Version:   go1.21.0
Git Commit:   5db42e86862ef42c59304c38aa583732fd80f178
Built:        Mon Aug 28 22:55:03 2023
OS/Arch:      darwin/arm64

Server:       Podman Engine
Version:      4.6.2
API Version:  4.6.2
Go Version:   go1.20.7
Built:        Wed Sep 13 04:07:26 2023
OS/Arch:      linux/arm64
```

2023-09-26 15:49 UTC, JohnNiang commented on docs/getting-started/install/podman.md
> +    podman run -it -d --name halo -p 8090:8090 -v ~/.halo2:/root/.halo2 halohub/halo:2.9
这里引用 [Podman run 命令文档](https://docs.podman.io/en/latest/markdown/podman-run.1.html#:~:text=If%20the%20source%20does%20not%20exist%2C%20Podman%20returns%20an%20error)：

> If a volume source is specified, it must be a path on the host or the name of a named volume. Host paths are allowed to be absolute or relative; relative paths are resolved relative to the directory Podman is run in. If the source does not exist, Podman returns an error. Users must pre-create the source files or directories.

所以，建议在执行命令之前提示用户提前创建好目录。

2023-09-27 04:03 UTC, JohnNiang reviewed
Hi @wangxiaoerYah ，可能还需要修改 <https://github.com/halo-dev/docs/blob/main/sidebars.js> 以保证在最新版的菜单中能显示对应的文档。

2023-09-27 04:33 UTC, JohnNiang reviewed
/lgtm

2023-09-27 05:04 UTC, ruibaby commented
@wangxiaoerYah 建议全局替换一下 `https://xxx.com`，使用 `https://localhost:8090`，虽然是示例域名，但 `xxx.com` 似乎是一个可访问（且不健康）的网站。

2023-09-27 05:11 UTC, JohnNiang commented
Hi @wangxiaoerYah and @ruibaby ，其实我更建议不在这里配置 external-url。后续更建议在配置文件中配置即可。这样用户在修改配置后只需要重启容器即可，而不是重建运行命令。

2023-09-27 05:16 UTC, JohnNiang commented
> > Hi @wangxiaoerYah and @ruibaby ，其实我更建议不在这里配置 external-url。后续更建议在配置文件中配置即可。这样用户在修改配置后只需要重启容器即可，而不是重建运行命令。
> 
> 噢噢,看来我的理解有误了,我一直都将ext url放在里面.我以为这是正确的运行方式.😂😂😂

参数配置形式一般作为快速开始或者分享复现步骤的时候比较有用，生产环境还是建议用 `~/.halo2/application.yaml` 的方式进行配置。

2023-09-27 05:21 UTC, ruibaby approved these changes
/lgtm

2023-09-27 05:22 UTC, merged

2023-09-27 05:24 UTC, ruibaby commented
>  其实我觉得应该直接写到数据库里,在第一次搭建时,最好有个类似于worldpress那种引导界面,让用户通过图形化配置.
然后如果迁移到新网址,怎么办呢,就是访问console管理界面时就不要验证是不是用户配置的域,等到用户登录了管理界面,前端或者后端再去检测当前域,提示用户要不要修改.

后续可以考虑在 Console 配置外部访问链接，目前 external-url 的意义更多的是一个主域名的意义（比如生成 sitemap 会需要域名来确定链接，邮件模板也需要这个域名来生成绝对地址），即便配置不正确也不会影响系统的访问。如果后续需要换域名，目前也只需要修改这个 external-url 参数并重建容器。

2023-09-27 05:27 UTC, ruibaby commented
> 参数配置形式一般作为快速开始或者分享复现步骤的时候比较有用，生产环境还是建议用 ~/.halo2/application.yaml 的方式进行配置。

如果要改，建议在未来某个合适的时候一起修改。目前建议文档为主，是怎么样就是怎么样，给用户太多的配置选择反而会造成困扰，尤其是最终目的都是一致的。

2023-09-27 05:28 UTC, JohnNiang commented
Hi @wangxiaoerYah ，现在之所以需要在配置文件中配置 `external-url`，主要是因为修改它后，文章、页面、分类、标签和菜单等的访问链接需要同步修改。这些操作重启 Halo 后才能生效。

2023-09-27 05:33 UTC, ruibaby commented
感谢 @wangxiaoerYah 参与贡献🌟