Update docker-compose.md
halo-dev/docs pull request #276
Opened 2023-11-07 18:09 UTC by clien9025

Mysql 的 yaml 配置文件中的 start_period 项修改；
以及 depends_on 的格式的修改

2023-11-08 02:56 UTC, JohnNiang requested changes
Hi @clien9025 ，感谢提交 PR！

2023-11-08 02:56 UTC, JohnNiang commented on versioned_docs/version-2.10/getting-started/install/docker-compose.md
> +          - halodb
这里建议添加上 `condition: service_healthy`。如果没有 condition 的话，Halo 可能在数据库还没有准备好就启动，会造成 Halo 容器多余一次或多次重启。

参考：

- https://docs.docker.com/compose/compose-file/05-services/#long-syntax-1

2023-11-08 02:56 UTC, JohnNiang commented on versioned_docs/version-2.10/getting-started/install/docker-compose.md
> +        image: halohub/halo:2.10.2
建议不加上 patch 版本。主要是为了每次发布 patch 版本的时候不用频繁修改文档。

2023-11-08 04:16 UTC, clien9025 commented on versioned_docs/version-2.10/getting-started/install/docker-compose.md
> +          - halodb
在 Docker Compose 文件的版本 3 中，condition 形式的 depends_on 是不支持的。所以应该使用数组形式来声明依赖关系，而不是使用映射（map）和条件。

2023-11-08 04:21 UTC, clien9025 commented on versioned_docs/version-2.10/getting-started/install/docker-compose.md
> +          - halodb
所以我改写成如下版本：
```
services:
  halo:
    image: halohub/halo:latest
    container_name: halo
    restart: on-failure
    depends_on:
      - halodb
    # 其他配置...
```

2023-11-12 05:46 UTC, ruibaby commented on versioned_docs/version-2.10/getting-started/install/docker-compose.md
> +          - halodb
我这边实际测试了一下，这样修改之后反而是有问题的：

<img width="1920" alt="图片" src="https://github.com/halo-dev/docs/assets/21301288/ef8e4ca6-e4f9-4a9c-826f-74d499993e04">
<img width="1920" alt="图片" src="https://github.com/halo-dev/docs/assets/21301288/3a942071-66a6-4d99-b38f-5db70abfd77d">

这样会让 Halo 和 MySQL 同时启动，就会造成 MySQL 容器还没有 ready，Halo 也无法启动。

根据文档 [docs.docker.com/compose/compose-file/05-services/#long-syntax-1](https://docs.docker.com/compose/compose-file/05-services/#long-syntax-1)，当前的配置方式才是正确的，我想知道你是遇到什么问题才进行这个修改的吗？

2023-11-16 15:22 UTC, clien9025 commented on versioned_docs/version-2.10/getting-started/install/docker-compose.md
> +          - halodb
````yaml
version: "3"

services:
  halo:
    image: halohub/halo:2.10.2
    container_name: halo
    restart: on-failure:3
    depends_on:
      - halodb
    networks:
      - halo_network
    volumes:
      - ./halo2:/root/.halo2
    ports:
      - "8090:8090"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/actuator/health/readiness"]
      interval: 30s
      timeout: 5s
      retries: 5
    command:
      - --spring.r2dbc.url=r2dbc:pool:mysql://halodb:3306/halo
      - --spring.r2dbc.username=root
      - --spring.r2dbc.password=zdasdasdad
      - --spring.sql.init.platform=mysql
      - --halo.external-url=http://123.12.123.123:8090/

  halodb:
    image: mysql:8.1.0
    container_name: halodb
    restart: on-failure:3
    networks:
      - halo_network
    command: 
      - --default-authentication-plugin=caching_sha2_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
      - --explicit_defaults_for_timestamp=true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./mysqlBackup:/data/mysqlBackup
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--silent"]
      interval: 3s
      retries: 5
    environment:
      - MYSQL_ROOT_PASSWORD=zdasdasdad
      - MYSQL_DATABASE=halo

networks:
  halo_network:

````
以上的yaml配置文件就是我本人的配置，我本人已经运行成功，博客也在使用中。还是我上述的观点（如下）：

> 在 Docker Compose 文件的版本 3 中，condition 形式的 depends_on 是不支持的。所以应该使用数组形式来声明依赖关系，而不是使用映射（map）和条件。
PS：上述的数据库的密码和地址请自行配置（本人已修改）

2023-11-16 15:27 UTC, clien9025 commented on versioned_docs/version-2.10/getting-started/install/docker-compose.md
> +          - halodb
> 我这边实际测试了一下，这样修改之后反而是有问题的：
> 
> <img alt="图片" width="1920" src="https://user-images.githubusercontent.com/21301288/282280059-ef8e4ca6-e4f9-4a9c-826f-74d499993e04.png"> <img alt="图片" width="1920" src="https://user-images.githubusercontent.com/21301288/282280065-3a942071-66a6-4d99-b38f-5db70abfd77d.png">
> 这样会让 Halo 和 MySQL 同时启动，就会造成 MySQL 容器还没有 ready，Halo 也无法启动。
> 
> 根据文档 [docs.docker.com/compose/compose-file/05-services/#long-syntax-1](https://docs.docker.com/compose/compose-file/05-services/#long-syntax-1)，当前的配置方式才是正确的，我想知道你是遇到什么问题才进行这个修改的吗？

我按照最新的DockerCompose中的yaml文件去配的时候，总是提示yaml文件有问题，说是：在 Docker Compose 文件的版本 3 中，condition 形式的 depends_on 是不支持的。所以我的yaml的配置文件才会这样修改

2023-11-16 15:28 UTC, ruibaby commented on versioned_docs/version-2.10/getting-started/install/docker-compose.md
> +          - halodb
> 在 Docker Compose 文件的版本 3 中，condition 形式的 depends_on 是不支持的。所以应该使用数组形式来声明依赖关系，而不是使用映射（map）和条件。

建议提供出处。

2023-11-16 16:58 UTC, JohnNiang commented on versioned_docs/version-2.10/getting-started/install/docker-compose.md
> +          - halodb
> 在 Docker Compose 文件的版本 3 中，condition 形式的 depends_on 是不支持的。所以应该使用数组形式来声明依赖关系，而不是使用映射（map）和条件。

请参考 Compose Spec：https://github.com/compose-spec/compose-go/blob/e0585709d30b89723d534c83cd5ac39acf11d4a8/schema/compose-spec.json#L184-L210

2023-11-17 08:27 UTC, clien9025 commented on versioned_docs/version-2.10/getting-started/install/docker-compose.md
> +          - halodb
> > 在 Docker Compose 文件的版本 3 中，condition 形式的 depends_on 是不支持的。所以应该使用数组形式来声明依赖关系，而不是使用映射（map）和条件。
> 
> 建议提供出处。

我的出处是GPT。按照GPT的建议修改完之后，我就能启动yaml的配置了。我使用halo官网最新的DockerCompose版本的yaml文件就启动不了我的halo服务器

2023-11-17 08:49 UTC, JohnNiang commented on versioned_docs/version-2.10/getting-started/install/docker-compose.md
> +          - halodb
Hi @clien9025 ，可以提供一下你的 Docker Compose CLI 的版本么？如果版本过低可能无法正常解析 docker-compose.yaml。

我的 Docker Compose CLI 版本如下：

```bash
~ docker-compose version
Docker Compose version v2.22.0-desktop.2
```

如果运行时不配置 condition，最终 Halo 也会正常运行起来，不过你可以观察一下，Halo 容器可能会重启多次才能启动起来，因为数据库容器虽然启动好了，但是数据库还没有准备好接收新的连接。加上 condition 就是为了等待数据库准备好接收新连接才去启动 Halo 容器。

2023-11-17 13:46 UTC, clien9025 commented on versioned_docs/version-2.10/getting-started/install/docker-compose.md
> +          - halodb
```shell
~# docker-compose version
docker-compose version 1.25.0, build unknown
docker-py version: 4.1.0
CPython version: 3.8.2
OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020
```

2023-11-19 14:33 UTC, ruibaby commented on versioned_docs/version-2.10/getting-started/install/docker-compose.md
> +          - halodb
Docker Compose 版本过旧，不支持我们文档提供的 depends_on 写法，[1.25.0](https://github.com/docker/compose/tree/1.25.0) 已经是 2019 年的版本了。

https://github.com/docker/compose/blob/4038169d96ca176542c5265e21f4b18ee64b1dd9/compose/config/config_schema_v3.0.json#L79

2023-11-21 03:14 UTC, clien9025 commented on versioned_docs/version-2.10/getting-started/install/docker-compose.md
> +          - halodb
> Docker Compose 版本过旧，不支持我们文档提供的 depends_on 写法，[1.25.0](https://github.com/docker/compose/tree/1.25.0) 已经是 2019 年的版本了。
> 
> https://github.com/docker/compose/blob/4038169d96ca176542c5265e21f4b18ee64b1dd9/compose/config/config_schema_v3.0.json#L79

好的，谢谢，了解了

2023-11-25 03:29 UTC, ruibaby commented on versioned_docs/version-2.10/getting-started/install/docker-compose.md
> +          - halodb
那我就关闭这个 PR 了。

2023-11-25 03:29 UTC, ruibaby commented
/close

2023-11-25 03:29 UTC, closed without merging

2024-02-08 14:43 UTC, clien9025 commented on versioned_docs/version-2.10/getting-started/install/docker-compose.md
> +          - halodb
ok