Add notification settings to user guide
halo-dev/docs pull request #292
Opened 2023-12-09 04:54 UTC by Anyexyz

2023-12-09 08:52 UTC, ruibaby requested changes

2023-12-09 08:52 UTC, ruibaby commented on docs/user-guide/settings.md
> +
列表语法中不应该有空行，否则单个列表项会被渲染成一个列表。

2023-12-09 08:52 UTC, ruibaby commented on docs/user-guide/settings.md
> +> 常见的 SMTP 服务器地址、端口号、加密方式如下：
建议列出常见邮箱服务商的文档即可。

2023-12-09 12:54 UTC, Anyexyz commented on docs/user-guide/settings.md
> +> 常见的 SMTP 服务器地址、端口号、加密方式如下：
这个是怕部分服务商文档变化，链接失效

2023-12-09 13:35 UTC, ruibaby reviewed
/lgtm

2023-12-10 14:23 UTC, JohnNiang approved these changes
Thanks for your contribution, @Anyexyz .

/approve

2023-12-10 14:24 UTC, ruibaby approved these changes

2023-12-10 14:26 UTC, merged