Refactor project build and run
halo-dev/docs pull request #308
Opened 2024-02-03 15:08 UTC by JohnNiang

This PR mainly adapts PR <https://github.com/halo-dev/halo/pull/5314>.

```release-note
None
```

2024-02-04 03:04 UTC, ruibaby requested changes

2024-02-04 03:04 UTC, ruibaby commented on docs/developer-guide/core/build.md
> +构建完成之后，在 Halo 项目下产生的 `application/build/libs/halo-${version}.jar` 即为构建完成的文件。
建议在这行下面添加 jar 部署方式的文档提示。

https://docs.halo.run/getting-started/install/jar-file

2024-02-04 03:04 UTC, ruibaby commented on docs/developer-guide/core/build.md
> +# 请替换成 ${tag_name}
应该是请替换 ${tag_name}？

2024-02-04 03:41 UTC, ruibaby reviewed
/lgtm

2024-02-04 03:43 UTC, guqing approved these changes

2024-02-06 06:27 UTC, JohnNiang commented
/ping @halo-dev/sig-docs

2024-02-06 06:30 UTC, ruibaby approved these changes
/lgtm

2024-02-06 06:32 UTC, merged