feat: modify ui service startup way
halo-dev/docs pull request #350
Opened 2024-05-10 15:35 UTC by mashirot

```
修改 UI 服务启动方式为直接从 pnpm 启动
```

2024-05-11 03:24 UTC, ruibaby requested changes

2024-05-11 03:24 UTC, ruibaby commented on docs/developer-guide/core/run.md
>  cd path/to/halo
```suggestion
cd path/to/halo/ui
pnpm install
pnpm dev
```

2024-05-11 03:24 UTC, ruibaby commented on docs/developer-guide/core/run.md
> +> 不建议使用以下方式, [原因](https://github.com/gradle/gradle/issues/7603)
我觉得直接改上面的命令就行了，这个提示可以不要。

2024-05-11 03:27 UTC, guqing commented on docs/developer-guide/core/run.md
>  cd path/to/halo
@ruibaby 这里不需要 build:packages 吗

2024-05-11 03:54 UTC, ruibaby commented on docs/developer-guide/core/run.md
>  cd path/to/halo
> @ruibaby 这里不需要 build:packages 吗

需要，已修改。

2024-05-17 07:40 UTC, ruibaby approved these changes
/lgtm

2024-05-17 07:42 UTC, merged