docs: add docs for plugin ExtensionGetter
halo-dev/docs pull request #388
Opened 2024-07-25 04:10 UTC by LIlGG

#### What this PR does / why we need it:

添加 ExtensionGetter 的开发者文档及示例。

see https://github.com/halo-dev/halo/pull/6365

#### Does this PR introduce a user-facing change?
```release-note
None
```

2024-07-25 09:00 UTC, JohnNiang requested changes

2024-07-25 09:00 UTC, JohnNiang commented on docs/developer-guide/plugin/api-reference/server/extension-getter.md
> +
缺少相关的代码示例。

2024-07-25 09:29 UTC, guqing requested changes

2024-07-25 09:29 UTC, guqing commented on docs/developer-guide/plugin/api-reference/server/extension-getter.md
> +description: 了解如何在插件中获取扩展
```suggestion
description: 了解如何在插件中使用 `ExtensionGetter` 获取扩展
```

2024-07-25 09:29 UTC, guqing commented on docs/developer-guide/plugin/api-reference/server/extension-getter.md
> +Halo 提供了丰富的扩展点，而插件不仅可以实现扩展点，也可以通过使用 `ExtensionGetter` 来获取 Halo 或其他插件所提供的扩展。
首先这篇文档的主要作用是介绍 ExtensionGetter 的使用，那么就直接干脆一点不要说插件扩展，这部分内容后续放在`与其他插件交互` 的章节目录下包括：插件如何被扩展，如何监听其他插件的共享事件和插件依赖等章节
```suggestion
在 Halo 插件开发中，`ExtensionGetter` 是一个重要的接口，用于获取和管理 Halo 或其他插件提供的扩展。它提供了多种方法来根据扩展点获取扩展，确保插件能够灵活地集成和使用各种扩展功能。
```

2024-07-25 09:29 UTC, guqing commented on docs/developer-guide/plugin/api-reference/server/extension-getter.md
> +关于插件如何实现扩展点的详细信息，请参考：[扩展点](./extension-points/index.md)。
```suggestion
`ExtensionGetter` 接口的定义如下：

public interface ExtensionGetter {

    /**
     * Get only one enabled extension from system configuration.
     *
     * @param extensionPoint is extension point class.
     * @return implementation of the corresponding extension point. If no configuration is found,
     * we will use the default implementation from application context instead.
     */
    <T extends ExtensionPoint> Mono<T> getEnabledExtension(Class<T> extensionPoint);

    /**
     * Get the extension(s) according to the {@link ExtensionPointDefinition} queried
     * by incoming extension point class.
     *
     * @param extensionPoint extension point class
     * @return implementations of the corresponding extension point.
     * @throws IllegalArgumentException if the incoming extension point class does not have
     *                                  the {@link ExtensionPointDefinition}.
     */
    <T extends ExtensionPoint> Flux<T> getEnabledExtensions(Class<T> extensionPoint);

    /**
     * Get all extensions according to extension point class.
     *
     * @param extensionPointClass extension point class
     * @param <T> type of extension point
     * @return a bunch of extension points.
     */
    <T extends ExtensionPoint> Flux<T> getExtensions(Class<T> extensionPointClass);
}

包括以下方法：

1. `getEnabledExtension(Class<T> extensionPoint)`: 获取一个在扩展设置中已启用的扩展。如果没有找到对应配置，将使用 Halo 中的默认扩展，如果 Halo 没有提供默认实现则找到一个由**已启用插件**提供的可用扩展。
2. `getEnabledExtensions(Class<T> extensionPoint)`: 根据传入的扩展点类获取所有已启用扩展。如果没有在扩展设置页面配置过则会返回所有可用的扩展。
3. `getExtensions(Class<T> extensionPointClass)`: 获取所有与扩展点类相关的扩展，不论有没有在扩展设置中启用它。

具体使用 `getEnabledExtension` 方法或者 `getEnabledExtensions` 方法取决于扩展点声明的 `type` 是 `SINGLETON` 还是 `MULTI_INSTANCE`。

通过使用 `ExtensionGetter`，开发者可以轻松地在插件中访问和管理各种扩展点，提升插件的功能和灵活性。

如果想了解 Halo 提供的扩展点请参考：[扩展点](./extension-points/index.md)。
```

2024-07-25 09:29 UTC, guqing commented on docs/developer-guide/plugin/api-reference/server/extension-getter.md
> +### 进阶使用
进阶使用的章节建议移除，后续放在 `与其他插件交互` 的章节目录下单独作为一章`插件如何被扩展`或者`插件如何定义自己的扩展点`

2024-07-25 10:06 UTC, guqing approved these changes
/approve

2024-07-26 02:27 UTC, JohnNiang approved these changes
/lgtm

2024-07-26 02:27 UTC, merged