docs: add image optimization documentation for theme development
halo-dev/docs pull request #405
Opened 2024-08-27 04:40 UTC by ruibaby

添加主题开发的图片优化文档。

/kind documentation

```release-note
None
```

2024-08-27 10:05 UTC, guqing requested changes

2024-08-27 10:05 UTC, guqing commented on docs/developer-guide/theme/image-optimization.md
> +- `url:string` - 图片地址。
```suggestion
- `uri:string` - 图片地址。
```

2024-08-27 10:05 UTC, guqing commented on docs/developer-guide/theme/image-optimization.md
> +### `thumbnail.gen(url,size)`
```suggestion
### `thumbnail.gen(uri,size)`
```

2024-08-27 10:05 UTC, guqing commented on docs/developer-guide/theme/image-optimization.md
> +`GET /apis/api.storage.halo.run/thumbnails/-/via-uri?uri=${url}&width={width}`
```suggestion
`GET /apis/api.storage.halo.run/thumbnails/-/via-uri?uri=${uri}&size={size}`
```

2024-08-27 10:05 UTC, guqing commented on docs/developer-guide/theme/image-optimization.md
> +- `width:number` - 缩略图尺寸，支持以下值：
- `size:string` - 缩略图尺寸，支持以下值：
  - `s` - 宽度 400px
  - `m` - 宽度 800px
  - `l` - 宽度 1200px
  - `xl` - 宽度 1600px

2024-08-27 10:05 UTC, guqing commented on docs/developer-guide/theme/image-optimization.md
> +  srcset="|/apis/api.storage.halo.run/thumbnails/-/via-uri?uri=/upload/post-cover.png&width=w400 400w,
改一下 width 为 size

2024-08-29 08:14 UTC, ruibaby commented on docs/developer-guide/theme/image-optimization.md
> +  srcset="|/apis/api.storage.halo.run/thumbnails/-/via-uri?uri=/upload/post-cover.png&size=s 400w,
请求接口缺少 /v1alpha1/

2024-09-01 14:50 UTC, guqing commented on docs/developer-guide/theme/image-optimization.md
> +- size:string - 缩略图尺寸，支持以下值：
```suggestion
- `size:string` - 缩略图尺寸，支持以下值：
```

2024-09-01 14:51 UTC, guqing commented on docs/developer-guide/theme/image-optimization.md
> +### `thumbnail.gen(uri,size)`
```suggestion
### `thumbnail.gen(uri, size)`
```

2024-09-01 14:53 UTC, guqing commented on docs/developer-guide/theme/image-optimization.md
> +  - s - 宽度 400px
这一片切少 "`" 包裹 但是上面的文档有

2024-09-01 15:03 UTC, ruibaby commented on docs/developer-guide/theme/image-optimization.md
> +  - s - 宽度 400px
已修改。

2024-09-01 15:06 UTC, guqing approved these changes
/lgtm

2024-09-01 15:49 UTC, merged