docs: update devtools documents
halo-dev/docs pull request #446
Opened 2024-10-25 09:35 UTC by guqing

### What this PR does?
更新 devtools 使用文档

```release-note
None
```

2024-10-25 13:34 UTC, ruibaby requested changes

2024-10-25 13:34 UTC, ruibaby commented on versioned_docs/version-2.20/developer-guide/plugin/basics/devtools.md
> +```yaml
同上。

2024-10-28 03:07 UTC, guqing commented on versioned_docs/version-2.20/developer-guide/plugin/basics/devtools.md
> +```yaml
Done

2024-10-28 03:07 UTC, guqing commented on docs/developer-guide/plugin/basics/devtools.md
> +```
Done

2024-10-28 06:30 UTC, ruibaby approved these changes
/lgtm

2024-10-28 06:32 UTC, merged