增加docker-compose安装方式
halo-dev/docs pull request #58
Opened 2022-03-28 09:30 UTC by MoshiCoCo

[增加docker-compose安装方式](https://github.com/halo-dev/docs/commit/a31d651969de6b5a4dde757023bfa553e6240be5)

2022-03-28 09:40 UTC, ruibaby commented
see https://deploy-preview-58--halo-docs.netlify.app/next/getting-started/install/docker-compose/

2022-03-28 09:40 UTC, ruibaby commented
/kind documentation
/cc @halo-dev/sig-docs

2022-03-28 09:49 UTC, ruibaby requested changes
感谢你的贡献，这里有几个可能需要修改的地方。

2022-03-28 09:49 UTC, ruibaby commented on docs/getting-started/install/docker-compose.md
> +1. 安装Docker-Compose
这里不建议提供 Docker Compose 的安装方式，一般我们假设使用者已经安装了 Docker Compose 即可。

2022-03-28 09:49 UTC, ruibaby commented on docs/getting-started/install/docker-compose.md
> +6. 启动Halod服务
```diff
- 6. 启动Halod服务
+ 6. 启动 Halo 服务
```

2022-03-28 09:49 UTC, ruibaby commented on docs/getting-started/install/docker-compose.md
> +5. 创建docker-compose.yaml
```diff
- 5. 创建docker-compose.yaml
+ 5. 创建 docker-compose.yaml
```

2022-03-28 09:49 UTC, ruibaby commented on docs/getting-started/install/docker-compose.md
> +Halo 在 Docker Hub 上发布的镜像为 [halohub/halo](https://hub.docker.com/r/halohub/halo)
似乎在下面 docker-compose.yaml 那里已经有了。

2022-03-28 09:51 UTC, ruibaby commented
另外，我认为 Docker Compose 的部署文档更多的是以一种示例的形式，一般来说，知道 Docker Compose 的同学能看懂这个 yaml 文件。没有使用过 Docker Compose 的同学我们也无法在此文档中把每个步骤都写详尽。

所以我认为在 https://github.com/halo-dev/docs/pull/58/files#diff-65e63a5f519ee2d2448d474e565fb3284cfc67c6225315e003e1f39fe4df0f0cR49 这个部分，可以提供多种形式的 yaml 描述文件，比如与 MySQL 一起编排等。

2022-03-28 09:54 UTC, JohnNiang reviewed
Hi @MoshiCoCo , thanks for your first contribution! I left some suggestions here, please take a moment to look at it.

2022-03-28 09:54 UTC, JohnNiang commented on docs/getting-started/install/docker-compose.md
> +
请移除多余的行。

2022-03-28 09:54 UTC, JohnNiang commented on docs/getting-started/install/docker-compose.md
> +
请移除多余的行

2022-03-28 09:54 UTC, JohnNiang commented on docs/getting-started/install/docker-compose.md
> +2. 创建 [工作目录](../prepare#工作目录)
```suggestion
2. 创建[工作目录](../prepare#工作目录)
```

2022-03-28 09:54 UTC, JohnNiang commented on docs/getting-started/install/docker-compose.md
> +3. 下载示例配置文件到 [工作目录](../prepare#工作目录)
```suggestion
3. 下载示例配置文件到[工作目录](../prepare#工作目录)
```

2022-03-28 09:54 UTC, JohnNiang commented on docs/getting-started/install/docker-compose.md
> +4. 编辑配置文件，配置数据库或者端口等，如需配置请参考 [配置参考](../config)
```suggestion
4. 编辑配置文件，配置数据库或者端口等，如需配置请参考[配置参考](../config)
```

2022-03-28 09:54 UTC, JohnNiang commented on docs/getting-started/install/docker-compose.md
> +5. 创建docker-compose.yaml
```suggestion
5. 创建 docker-compose.yaml
```

2022-03-28 09:54 UTC, JohnNiang commented on docs/getting-started/install/docker-compose.md
> +查看最新版本镜像：<https://hub.docker.com/r/halohub/halo> ，我们推荐使用具体版本号的镜像，但也提供了 `latest` 标签的镜像，它始终是最新的。
```suggestion
查看最新版本镜像：<https://hub.docker.com/r/halohub/halo>，我们推荐使用具体版本号的镜像，但也提供了 `latest` 标签的镜像，它始终是最新的。
```

2022-03-28 09:54 UTC, JohnNiang commented on docs/getting-started/install/docker-compose.md
> +6. 启动Halod服务
```suggestion
6. 启动 Halo 服务
```

2022-03-28 09:54 UTC, JohnNiang commented on docs/getting-started/install/docker-compose.md
> +注意：此命令默认使用自带的 `H2 Database `数据库。如需使用` MySQL`，请参考：[使用 Docker 部署 Halo 和 MySQL](./other/docker-mysql) 的内容将 `datasource` 配置更改为`MySQL`的配置。
```suggestion
注意：此命令默认使用自带的 `H2 Database` 数据库。如需使用 `MySQL`，请参考：[使用 Docker 部署 Halo 和 MySQL](./other/docker-mysql) 的内容将 `datasource` 配置更改为 `MySQL` 的配置。
```

2022-03-28 09:54 UTC, JohnNiang commented on docs/getting-started/install/docker-compose.md
> +- **image：** 容器镜像版本，默认为`halohub/halo:1.5.0`，如果使用最新请使用 `halohub/halo:latest`
```suggestion
- **image：** 容器镜像版本，默认为 `halohub/halo:1.5.0`，如果使用最新请使用 `halohub/halo:latest`
```

2022-03-28 09:54 UTC, JohnNiang commented on docs/getting-started/install/docker-compose.md
> +- **volumes：** 工作目录映射。形式为：-v 宿主机路径:/root/.halo，后者不能修改。
```suggestion
- **volumes：** 工作目录映射。形式为：`-v 宿主机路径:/root/.halo`，后者不能修改。
```

2022-03-28 09:57 UTC, MoshiCoCo commented
> 另外，我认为 Docker Compose 的部署文档更多的是以一种示例的形式，一般来说，知道 Docker Compose 的同学能看懂这个 yaml 文件。没有使用过 Docker Compose 的同学我们也无法在此文档中把每个步骤都写详尽。
> 
> 所以我认为在 https://github.com/halo-dev/docs/pull/58/files#diff-65e63a5f519ee2d2448d474e565fb3284cfc67c6225315e003e1f39fe4df0f0cR49 这个部分，可以提供多种形式的 yaml 描述文件，比如与 MySQL 一起编排等。

很好的修改建议，后续我会修改这个 PR，增加 Halod+MySQL 方式的docker-compose.yaml。

2022-03-28 09:59 UTC, MoshiCoCo commented
> thanks for your first contribution! I left some suggestions here, please take a moment to look at it.

@JohnNiang  In response to these suggestions you made, I will finish editing them later.❤

2022-03-28 14:43 UTC, JohnNiang requested changes
请保证英文前后都有合理的空格。

2022-03-28 14:43 UTC, JohnNiang commented on docs/getting-started/install/docker-compose.md
> +注意：如果您未在 application.yaml 中修改数据源配置，使用此命令启动则会默认使用自带的 `H2 Database`数据库。如需使用`MySQL`，请参考：[使用 Docker 部署 Halo 和 MySQL](./other/docker-mysql) 的内容将 `datasource` 配置更改为`MySQL`的配置。
```suggestion
注意：如果您未在 application.yaml 中修改数据源配置，使用此命令启动则会默认使用自带的 `H2 Database` 数据库。如需使用 `MySQL`，请参考：[使用 Docker 部署 Halo 和 MySQL](./other/docker-mysql) 的内容将 `datasource` 配置更改为 `MySQL` 的配置。
```

2022-03-28 14:43 UTC, JohnNiang commented on docs/getting-started/install/docker-compose.md
> +- **image：** 容器镜像版本，默认为`halohub/halo:1.5.0`。如果需要使用最新版本请使用 `halohub/halo:latest`。
```suggestion
- **image：** 容器镜像版本，默认为 `halohub/halo:1.5.0`。如果需要使用最新版本请使用 `halohub/halo:latest`。
```

2022-03-28 14:44 UTC, JohnNiang commented
/retitle Add installation document using docker-compose

2022-03-28 14:50 UTC, guqing commented
/hold

2022-03-28 14:54 UTC, guqing commented
感谢你的贡献👏👏 我们会在测试之后再次 review

2022-03-29 12:31 UTC, ruibaby commented
@MoshiCoCo 我感觉把这个文档放在这里更好：

<img width="715" alt="image" src="https://user-images.githubusercontent.com/21301288/160611628-8722d268-2889-4dca-be34-31dff66cda87.png">

你觉得呢，因为我认为我们基础的文档仅提供 Jar 和 Docker 最简单的流程即可。

2022-03-29 12:33 UTC, MoshiCoCo commented
> @MoshiCoCo 我感觉把这个文档放在这里更好：
> 
> <img alt="image" width="715" src="https://user-images.githubusercontent.com/21301288/160611628-8722d268-2889-4dca-be34-31dff66cda87.png">
> 
> 你觉得呢，因为我认为我们基础的文档仅提供 Jar 和 Docker 最简单的流程即可。

说的有道理，我觉得没问题。😄

2022-03-30 00:34 UTC, JohnNiang approved these changes
/lgtm

2022-03-30 05:13 UTC, ruibaby requested changes

2022-03-30 05:13 UTC, ruibaby commented on docs/getting-started/install/other/docker-compose.md
> +      - ./:/root/.halo
这里不应该是 `./`，因为上面创建的工作目录就是 `~/.halo`

2022-03-30 05:13 UTC, ruibaby commented on docs/getting-started/install/other/docker-compose.md
> +3. 编辑配置文件，配置数据库或者端口等，如需配置请参考 [配置参考](../../config)
```suggestion
3. 编辑配置文件，配置数据库或者端口等，如需配置请参考[配置参考](../../config)
```

2022-03-30 05:13 UTC, ruibaby commented on docs/getting-started/install/other/docker-compose.md
> +** Halo+MySQL+Redis **
```suggestion
** Halo + MySQL + Redis **
```

2022-03-30 05:13 UTC, ruibaby commented on docs/getting-started/install/other/docker-compose.md
> +4. 创建 docker-compose.yaml
```suggestion
4. 创建 `docker-compose.yaml`
```

2022-03-30 05:13 UTC, ruibaby commented on docs/getting-started/install/other/docker-compose.md
> +      ## 此处需要输入自定义mysql密码
```suggestion
      ## 此处需要输入自定义 MySQL 密码
```

2022-03-30 05:13 UTC, ruibaby commented on docs/getting-started/install/other/docker-compose.md
> +    ## 此处需要输入自定义redis密码
```suggestion
    ## 此处需要输入自定义 Redis 密码
```

2022-03-30 05:13 UTC, ruibaby commented on docs/getting-started/install/other/docker-compose.md
> +    # 此处的地址应该使用docker-compose.yaml中配置的MySQL地址和密码
```suggestion
    # 此处的地址应该使用 docker-compose.yaml 中配置的 MySQL 地址和密码
```

2022-03-30 05:13 UTC, ruibaby commented on docs/getting-started/install/other/docker-compose.md
> +    # 此处的地址应该使用docker-compose.yaml中配置的Redis地址和密码
```suggestion
    # 此处的地址应该使用 docker-compose.yaml 中配置的 Redis 地址和密码
```

2022-03-30 05:13 UTC, ruibaby commented on docs/getting-started/install/other/docker-compose.md
> +注意：如果您未在 application.yaml 中修改数据源配置，使用此命令启动则会默认使用自带的 `H2 Database` 数据库。如需使用 `MySQL`，请参考：[使用 Docker 部署 Halo 和 MySQL](./docker-mysql) 的内容将 `datasource` 配置更改为 `MySQL` 的配置。
```suggestion
注意：如果您未在 `application.yaml` 中修改数据源配置，使用此命令启动则会默认使用自带的 `H2 Database` 数据库。如需使用 `MySQL`，请参考：[使用 Docker 部署 Halo 和 MySQL](./docker-mysql) 的内容将 `datasource` 配置更改为 `MySQL` 的配置。
```

2022-03-30 05:13 UTC, ruibaby commented on docs/getting-started/install/other/docker-compose.md
> +      - $PWD/:/root/.halo
```suggestion
      - ~/.halo:/root/.halo
```

2022-03-30 05:13 UTC, ruibaby commented on docs/getting-started/install/other/docker-compose.md
> +        ipv4_address: 172.19.0.4
这里是出于什么目的指定一个 ipv4_address 呢，我的理解是，创建了 halo_net 的 network 之后，MySQL 或者 Redis 当中的 url 可以使用 halo_net。

2022-03-30 05:13 UTC, ruibaby commented on docs/getting-started/install/other/docker-compose.md
> +  mysql_db:
```suggestion
  halo_mysql:
```

建议加上 `halo_` 前缀，在 docker ps -a 查阅的时候方便区分。

2022-03-30 05:13 UTC, ruibaby commented on docs/getting-started/install/other/docker-compose.md
> +  redis_db:
```suggestion
  halo_redis:
```

2022-03-30 05:13 UTC, ruibaby commented on docs/getting-started/install/other/docker-compose.md
> +    url: jdbc:mysql://172.19.0.2:3306/halodb?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
如上所述，这里应该可以这样写：`jdbc:mysql://halo_net:3306/halodb?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true`

2022-03-30 05:13 UTC, ruibaby commented on docs/getting-started/install/other/docker-compose.md
> +      - $PWD/mysql/var/lib/mysql:/var/lib/mysql
这里我个人建议指定在 ~/.halo 目录下，下面 Redis 也是。

2022-03-30 05:14 UTC, ruibaby commented
你好 @MoshiCoCo ，上面有一写 Change Requests 是可以直接点击接受的，不需要在本地修改推送，如：

<img width="626" alt="image" src="https://user-images.githubusercontent.com/21301288/160756208-1756aa6e-399f-4d71-99fb-cb581a88b1b4.png">

2022-03-30 05:15 UTC, ruibaby commented
`Halo 基础版本` 部分已经测试，`Halo + MySQL + Redis` 因为我是 arm 的设备。MySQL 没有提供 arm 的镜像，所以暂未测试，稍后我会找一台机器测试一下。

2022-03-30 05:20 UTC, ruibaby commented on docs/getting-started/install/other/docker-compose.md
> +  mysql_db:
> ~~建议加上 `halo_` 前缀，在 docker ps -a 查阅的时候方便区分。~~

看到了 `container_name` 设置，这条可以忽略。

2022-03-30 05:28 UTC, ruibaby requested changes

2022-03-30 05:28 UTC, ruibaby commented on docs/getting-started/install/other/docker-compose.md
> +      - MYSQL_ROOT_PASSWORD = mysqlpass
=号之间应该不能有空格

可能还需要指定 `MYSQL_DATABASE`，并在下面 application.yaml 中说明。

2022-03-30 07:04 UTC, MoshiCoCo commented
**文档格式的修改我已经在页面上处理了* * 

上面修改和回复也比较多了 ，不便于查看，我梳理下目前仍存在的问题。

1. 容器名字。
这里已经指定了`halo-`前缀，服务名依旧是mysql_db和redis_db，这里如果要修改，需要同步修改depends_on部分的名称。

2. 针对你提出来的 halo 和mysql 以及redis 目录映射的问题.

目前的配置：

halo的
```yaml
    - ./:/root/.halo
```
mysql的
```yaml
    - $PWD/mysql/mysqlBackup:/data/mysqlBackup
    - $PWD/mysql/var/lib/mysql:/var/lib/mysqlo
```
redis的
```yaml
      - $PWD/redis/data:/data
      - $PWD/redis/logs:/logs
```

由于我们在步骤1 创建了 ~/.halo 目录，并且cd进去了，所以我们后续所有的操作均是在 ~/.halo 完成的。以上配置均表示映射到当前目录，其中redis和mysql会映射到 ~/.halo/redis 和  ~/.halo/mysql 。

按照你的建议，改成 绝对路径的形式也是没问题的。改动后大致是这个样子。


halo的
```yaml
    - ~/.halo:/root/.halo
```
mysql的
```yaml
    - ~/.halo/mysql/mysqlBackup:/data/mysqlBackup
    - ~/.halo/mysql/var/lib/mysql:/var/lib/mysqlo
```
redis的
```yaml
      - ~/.halo/redis/data:/data
      - ~/.halo/redis/logs:/logs
```

3. docker-compose网络的问题。
```yaml
networks:
  halo_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16
```

这里创建了一个halo_net的网络，采用bridge方式，并且通过ipam（IP Address Management Driver）指定了子网（172.19.0.0/16），在容器配置中也为容器指定了一个类似于 （172.19.0.4）的固定地址。 这样做的目的是为了防止每次down up导致的容器地址变化，如果采用host模式就不会有这个问题。

2022-03-30 07:10 UTC, MoshiCoCo commented
@ruibaby  @JohnNiang 

**文档格式的修改我已经在页面上处理了* * 

上面修改和回复也比较多了 ，不便于查看，我梳理下目前仍存在的问题。

1. 容器名字。
这里已经指定了`halo-`前缀，服务名依旧是mysql_db和redis_db，这里如果要修改，需要同步修改depends_on部分的名称。

2. 针对你提出来的 halo 和mysql 以及redis 目录映射的问题.

目前的配置：

halo的
```yaml
    - ./:/root/.halo
```
mysql的
```yaml
    - $PWD/mysql/mysqlBackup:/data/mysqlBackup
    - $PWD/mysql/var/lib/mysql:/var/lib/mysqlo
```
redis的
```yaml
      - $PWD/redis/data:/data
      - $PWD/redis/logs:/logs
```

由于我们在步骤1 创建了 ~/.halo 目录，并且cd进去了，所以我们后续所有的操作均是在 ~/.halo 完成的。以上配置均表示映射到当前目录，其中redis和mysql会映射到 ~/.halo/redis 和  ~/.halo/mysql 。

我测试时的实际目录结构

```bash
drwxr-xr-x  7 root root 4096 Mar 28 23:03 ./
drwxr-xr-x 22 root root 4096 Mar 28 21:08 ../
-rw-r--r--  1 root root  627 Mar 28 21:52 application.yaml
-rw-r--r--  1 root root 1389 Mar 28 22:03 docker-compose.yml
drwxr-xr-x  2 root root 4096 Mar 28 21:14 logs/
drwxr-xr-x  4 root root 4096 Mar 28 21:13 mysql/
drwxr-xr-x  4 root root 4096 Mar 28 21:13 redis/
drwxr-xr-x  2 root root 4096 Mar 28 22:05 static/
drwxr-xr-x  3 root root 4096 Mar 28 22:05 templates/
```

按照你的建议，这里改成绝对路径的形式也是没问题的。改动后大致是这个样子。

halo的
```yaml
    - ~/.halo:/root/.halo
```
mysql的
```yaml
    - ~/.halo/mysql/mysqlBackup:/data/mysqlBackup
    - ~/.halo/mysql/var/lib/mysql:/var/lib/mysqlo
```
redis的
```yaml
      - ~/.halo/redis/data:/data
      - ~/.halo/redis/logs:/logs
```

3. docker-compose网络的问题。
```yaml
networks:
  halo_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16
```

这里创建了一个halo_net的网络，采用bridge方式，并且通过ipam（IP Address Management Driver）指定了子网（172.19.0.0/16），在容器配置中也为容器指定了一个类似于 （172.19.0.4）的固定地址。 这样做的目的是为了防止每次down up导致的容器地址变化，如果采用host模式就不会有这个问题，如果直接使用halo_net 去连接，应该时访问不到mysql和redis的，用服务名应该可以。


其他问题： 是否需要配置db，在application.yaml中的数据源已经指定了db，我的理解是，如果用户具备root的数据库访问权限，按理说会自动建库建表。如果这里halo没处理，则需要使用root用户访问进去创建一个名称为halodb的schema，这部分内容docker中的文档都有了。

2022-03-30 07:14 UTC, ruibaby commented
> 如果这里halo没处理

目前是需要手动创建数据库的，所以我觉得需要在容器初始化的时候创建数据库，否则 Halo 应该是无法正常启动的。

2022-03-30 07:15 UTC, ruibaby commented
> 这里创建了一个halo_net的网络，采用bridge方式，并且通过ipam（IP Address Management Driver）指定了子网（172.19.0.0/16），在容器配置中也为容器指定了一个类似于 （172.19.0.4）的固定地址。 这样做的目的是为了防止每次down up导致的容器地址变化，如果采用host模式就不会有这个问题，如果直接使用halo_net 去连接，应该时访问不到mysql和redis的，用服务名应该可以。

lgtm

2022-03-30 08:30 UTC, guqing approved these changes
/lgtm
/approve
/unhold

2022-03-30 08:38 UTC, ruibaby commented
/hold

2022-03-30 13:20 UTC, MoshiCoCo commented
@ruibaby  新增了在MySQL容器启动阶段创建数据库schema。
@guqing 劳烦重新测试。

2022-03-31 04:25 UTC, guqing requested changes

2022-03-31 04:25 UTC, guqing commented on docs/getting-started/install/other/docker-compose.md
> +    url: jdbc:mysql://172.19.0.2:3306/halodb?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
@MoshiCoCo 这里的url应该写成 mysql_db即 `url: jdbc:mysql://mysql_db:3306/halodb?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true`
然后把所有写固定ipv4的地方都去掉吧，这是最简单的方式，刚才我试了一下用你写的ipv4网络不互通，昨天测的时候被改了一下忽略了这一点没发现

2022-03-31 04:25 UTC, guqing commented on docs/getting-started/install/other/docker-compose.md
> +mkdir init && touch ./init/init.sql
将 ./init/init.sql 改为 ~/.halo/init/init.sql 可以提高容错率，有些用户不按操作来会忽略当前目录这一点

2022-03-31 04:25 UTC, guqing commented on docs/getting-started/install/other/docker-compose.md
> +    restart: unless-stopped
所有指定restart的地方都应该配置 restart_policy 来设置，当容器意外退出后一直循环重启是很不好的，应该指定重启频率间隔及尝试次数

2022-03-31 04:25 UTC, guqing commented on docs/getting-started/install/other/docker-compose.md
> +      - $PWD/:/root/.halo
这些$PWD的引用你可以通过在文档开头说明一个 `export HALO_WORKDIR=~/.halo` 然后来后续文档中将`$PWD`替换为`$HALO_WORKDIR`的方式来使用, 这样不仅容错高而且书写也方便

2022-03-31 07:25 UTC, MoshiCoCo commented
@guqing  
1. 已经把所有的$PWD的使用调整为 绝对路径~/.halo
2. 连接mysql和redis的地址调整为redis_db和mysql_db ，不再使用指定的服务名。

按照文档我在干净的环境中重试了，并未复现几个地址网路不互通的情况。

1. mysql 容器正常初始化（正常执行了initsql），redis容器正常初始化。
![image](https://user-images.githubusercontent.com/17582066/161000486-6495e4c6-2f6c-4790-84b9-a94f76c8b5d1.png)
![image](https://user-images.githubusercontent.com/17582066/161000517-7611c637-8eaa-47fa-87d0-4018b9cc0343.png)

2. halo容器启动后，正常在mysql halodb中创建了表。
![image](https://user-images.githubusercontent.com/17582066/161000303-1ec2193e-b4d9-47a5-963f-43425011be30.png)
![image](https://user-images.githubusercontent.com/17582066/161000357-f1a61799-14a1-4d8a-a7b6-3f57d58d667d.png)

3. 页面上完成首次初始化后， redis中正常缓存了key
![image](https://user-images.githubusercontent.com/17582066/161000696-dee4993e-2948-4266-bafa-e8b92486f126.png)


如果几个地址不互通，是没办法正常在halo-self容器中访问redis-db和mysql-db的

2022-03-31 07:31 UTC, guqing commented
@MoshiCoCo 非常感谢你的付出，我已经重新测试过了，目前工作的很好，开始进入合并流程🙆‍♀️🙆‍♀️

2022-03-31 07:31 UTC, guqing approved these changes
/lgtm
/approve
/unhold

2022-03-31 07:34 UTC, ruibaby approved these changes
/lgtm

/approve

感谢你的贡献。🎉

2022-03-31 07:36 UTC, guqing commented
/close

2022-03-31 07:36 UTC, closed without merging