add docker-compose upgrade method
halo-dev/docs pull request #65
Opened 2022-03-31 10:51 UTC by MoshiCoCo

add docker-compose upgrade method

2022-03-31 13:39 UTC, ruibaby commented
你好 @MoshiCoCo ，感谢你的贡献，个人建议可以将这部分文档追加到 docker-compose.md 这个文件中。

2022-03-31 13:39 UTC, ruibaby requested changes

2022-03-31 13:39 UTC, ruibaby commented on docs/getting-started/upgrade.md
> +执行更新命令：
```suggestion
启动容器组：
```

2022-03-31 21:29 UTC, MoshiCoCo commented
> 你好 @MoshiCoCo ，感谢你的贡献，个人建议可以将这部分文档追加到 docker-compose.md 这个文件中。

ok，已经移动到 docker-compose.md 中

2022-03-31 21:33 UTC, MoshiCoCo commented
@ruibaby 在 upgrade.md 末尾加了一个空行，不然pnpm lint 总是提示
```bash 
Finding: ./docs/**/*.md ./versioned_docs/version-1.5.0/**/*.md
Linting: 59 file(s)
Summary: 1 error(s)
docs/getting-started/upgrade.md:119:67 MD047/single-trailing-newline Files should end with a single newline character
```

不清楚是不是我姿势不对。

2022-04-01 02:18 UTC, guqing commented
> @ruibaby 在 upgrade.md 末尾加了一个空行，不然pnpm lint 总是提示
> ```bash 
> Finding: ./docs/**/*.md ./versioned_docs/version-1.5.0/**/*.md
> Linting: 59 file(s)
> Summary: 1 error(s)
> docs/getting-started/upgrade.md:119:67 MD047/single-trailing-newline Files should end with a single newline character
> ```
> 
> 不清楚是不是我姿势不对。
> 

文件末尾的确是需要一个空行 这是正常现象

2022-04-05 14:23 UTC, ruibaby approved these changes
/lgtm

2022-04-05 14:23 UTC, ruibaby commented
/approve

2022-04-05 14:24 UTC, ruibaby commented
/retitle docs: add docker-compose upgrade method

2022-04-05 14:25 UTC, guqing approved these changes
/lgtm

2022-04-05 15:07 UTC, merged

2022-04-06 02:16 UTC, ruibaby commented
你好 @MoshiCoCo 感谢你的贡献，此 PR 已经合并。有个小问题需要注意下，在你后续贡献的时候，我们建议从 https://github.com/halo-dev/docs 的 main 分支切新的分支修改，且各个修改应该在不同的分支，否则可能会导致一些 commit 混乱的问题。可以按照以下步骤：

添加主仓库到 upstream：

```bash
git remote add upstream git@github.com:halo-dev/docs.git
```

更新主仓库的提交：

```bash
git fetch --all

git merge upstream/main

git push 
```

新建分支修改：

```bash
git checkout upstream/main

git checkout -b docs/xxx
```