docs: improve docker compose documentations
halo-dev/docs pull request #74
Opened 2022-04-15 13:13 UTC by ruibaby

优化使用 Docker Compose 部署 Halo 的文档，主要以下几个改动：

1. 使用单独的文件夹托管数据和 docker-compose.yaml 文件。
2. 使用 Docker 环境变量代替通过 application.yaml 文件来配置。
3. 修改使用 MySQL 镜像时，创建数据库的方式。
4. 新增仅使用 Halo + MySQL 的配置。

已经对三种情况做了创建，更新，销毁，重建的测试。如果大家的电脑为 arm 架构的 CPU，可以将 MySQL 的镜像改为 `mariadb:latest` 进行测试。

/kind documentation
/cc @halo-dev/sig-docs @halo-dev/sig-infra

2022-04-15 15:53 UTC, guqing reviewed
/lgtm

2022-04-15 16:01 UTC, JohnNiang commented on versioned_docs/version-1.5.2/getting-started/install/other/docker-compose.md
> +此文档提供三种场景的 Docker-Compose 配置文件，请根据你的需要选择一种。
```suggestion
此文档提供三种场景的 Docker Compose 配置文件，请根据你的需要选择一种。
```

2022-04-15 16:01 UTC, JohnNiang commented on docs/getting-started/install/other/docker-compose.md
> +```yaml {22-23,29,49,62}
`{22-23,29,49,62}` 这是什么语法，可以提供一下参考链接么

2022-04-15 16:34 UTC, ruibaby commented on docs/getting-started/install/other/docker-compose.md
> +```yaml {22-23,29,49,62}
https://docusaurus.io/docs/markdown-features/code-blocks#highlighting-with-metadata-string

就是高亮某行代码。可以在这看实际效果：https://deploy-preview-74--halo-docs.netlify.app/getting-started/install/other/docker-compose

2022-04-15 16:46 UTC, ruibaby commented
/hold

2022-04-16 03:45 UTC, MoshiCoCo commented
@ruibaby rui 大致看了下，没有什么问题。 但是我注意到depends_on 只保留了mysql容器。 不清楚某些情况下（比如第一次启动时，需要拉取容器镜像，拉镜像的时候可能redis镜像是最后拉取成功的，相应的redis容器可能会在halo启动后才开始启动），redis 容器启动是否会在halo容器之后开始启动。 如果是这种情况下，可能会导致halo连接redis失败。
```yaml
    depends_on:
      - halo_mysql
```

虽然depends_on也仅能保证容器的启动顺序（非reday顺序），而非启动成功进入reday状态后再去启动下个容器。 但是能一定程度解决上面的问题。（如果我上面的理解没问题的话。 

这里最佳的方案其实是通过一个wait-for脚本，在halo启动后，通过以容器command命令的方式检查mysql和redis是否已经是reday状态。但是这个又不是很必要，实际上redis的启动其实非常快，绝大部分情况下是可以在halo启动前完成初始化。

2022-04-16 04:14 UTC, ruibaby commented
@MoshiCoCo 哈哈，忘了加。

2022-04-16 04:59 UTC, ruibaby commented
/unhold

2022-04-16 07:04 UTC, JohnNiang requested changes

2022-04-16 07:04 UTC, JohnNiang commented on docs/getting-started/install/other/docker-compose.md
> +A. 仅创建 Halo 实例（使用默认的 H2 数据库）：
建议用缩进序号的方式替代字母序号。

2022-04-16 07:31 UTC, ruibaby commented on docs/getting-started/install/other/docker-compose.md
> +A. 仅创建 Halo 实例（使用默认的 H2 数据库）：
那这样就得完全按照语法规定来做了，我们目前文档这种步骤虽然使用了 list 的语法，但其实列表项下方的内容块是没有按照语法要求的，如果要遵循语法的渲染规则，列表项下方的内容块必须得缩进，否则没有办法渲染出你说的这样的效果，已经修改了文档的列表内容缩进，可以在 netlify 上预览下。

2022-04-16 07:57 UTC, JohnNiang reviewed
/lgtm

2022-04-16 14:03 UTC, guqing commented
/lgtm

2022-04-16 14:05 UTC, guqing commented
/approve

2022-04-16 14:05 UTC, merged