增加kubernetes环境中部署halo文档
halo-dev/docs pull request #89
Opened 2022-08-09 13:45 UTC by marionxue

2022-08-09 14:14 UTC, ruibaby commented on docs/getting-started/install/other/kubernetes.md
> +- `data_source_url`: 以MySQL作为数据存储，halo使用jdbc驱动连接，其中 `10.0.1.13:33306` 为MySQL服务的IP地址和端口号，`halodb` 为halo所需要的数据库。
```suggestion
- `data_source_url`: 以 MySQL 作为数据存储，Halo 使用 JDBC 驱动连接，其中 `10.0.1.13:33306` 为 MySQL 服务的 IP 地址和端口号，`halodb` 为 Halo 所需要的数据库。
```

2022-08-09 14:15 UTC, ruibaby commented on docs/getting-started/install/other/kubernetes.md
> +- `datasource_username`: halo连接MySQL的`用户名`
```suggestion
- `datasource_username`: Halo 连接 MySQL 的用户名
```

2022-08-09 14:15 UTC, ruibaby commented on docs/getting-started/install/other/kubernetes.md
> +- `datasource_password`: halo连接MySQL时 `datasource_username` 的密码
```suggestion
- `datasource_password`: Halo 连接 MySQL 时 `datasource_username` 的密码
```

2022-08-09 14:15 UTC, ruibaby commented on docs/getting-started/install/other/kubernetes.md
> +- `-n`: 表示此secret所在命名空间
```suggestion
- `-n`: 表示此 Secret 所在命名空间
```

2022-08-09 14:15 UTC, ruibaby commented on docs/getting-started/install/other/kubernetes.md
> +1. 在MySQL中创建以上脚本中预先定义好的用户名、密码、以及 halo 运行所需要的数据库 `halodb`，以下以 `mysql:8.0.30` 为例
```suggestion
1. 在 MySQL 中创建以上脚本中预先定义好的用户名、密码、以及 Halo 运行所需要的数据库 `halodb`，以下以 `mysql:8.0.30` 为例
```

2022-08-09 14:17 UTC, ruibaby commented on docs/getting-started/install/other/kubernetes.md
> +在 k8s 中运行 halo，会涉及到`主题`、静态资源如`上传本地图片`等需要持久化到数据卷中，为了后期的数据迁移，需要配置持久卷存储这些数据，此处我们使用本地存储。
```suggestion
在 kubernetes 中运行 Halo，会涉及到 `主题`、`上传的附件` 等数据需要持久化到数据卷中，为了后期的数据迁移，需要配置持久卷存储这些数据，此处我们使用本地存储。
```

2022-08-09 14:17 UTC, ruibaby commented on docs/getting-started/install/other/kubernetes.md
> +    path: "/data/halo" # 此目录为halo的数据目录
```suggestion
    path: "/data/halo" # 此目录为 Halo 的数据目录
```

2022-08-09 14:17 UTC, ruibaby commented on docs/getting-started/install/other/kubernetes.md
> +创建 `halo.deployment.yaml` 文件，定义 halo 服务运行状态
```suggestion
创建 `halo.deployment.yaml` 文件，定义 Halo 服务运行状态
```

2022-08-09 14:17 UTC, ruibaby commented on docs/getting-started/install/other/kubernetes.md
> +  revisionHistoryLimit: 5 # deployment历史保留数量
```suggestion
  revisionHistoryLimit: 5 # deployment 历史保留数量
```

2022-08-09 14:18 UTC, ruibaby commented on docs/getting-started/install/other/kubernetes.md
> +            limits: # 定义halo服务资源使用
```suggestion
            limits: # 定义 Halo 服务资源使用
```

2022-08-09 14:18 UTC, ruibaby commented on docs/getting-started/install/other/kubernetes.md
> +          env: # halo的配置均以环境变量的方式配置
```suggestion
          env: # Halo 的配置均以环境变量的方式配置
```

2022-08-09 14:18 UTC, ruibaby commented on docs/getting-started/install/other/kubernetes.md
> +                  key: data_source_url # 从secert中读取数据源信息
```suggestion
                  key: data_source_url # 从 Secret 中读取数据源信息
```

2022-08-09 14:18 UTC, ruibaby commented on docs/getting-started/install/other/kubernetes.md
> +            - name: SPRING_DATASOURCE_USERNAME # 从secert中读取halo数据用户
```suggestion
            - name: SPRING_DATASOURCE_USERNAME # 从 Secret 中读取 Halo 数据用户
```

2022-08-09 14:19 UTC, ruibaby commented on docs/getting-started/install/other/kubernetes.md
> +            - name: SPRING_DATASOURCE_PASSWORD # 从secert中读取halo数据用户的密码
```suggestion
            - name: SPRING_DATASOURCE_PASSWORD # 从 Secret 中读取 Halo 数据用户的密码
```

2022-08-09 14:20 UTC, ruibaby commented on docs/getting-started/install/other/kubernetes.md
> +            - mountPath: /root/.halo # 配置halo的数据目录
```suggestion
            - mountPath: /root/.halo # 配置 Halo 的数据目录
```

2022-08-09 14:20 UTC, ruibaby commented on docs/getting-started/install/other/kubernetes.md
> +创建 `halo.svc.yaml` 文件，声明 halo 的暴露方式
```suggestion
创建 `halo.svc.yaml` 文件，声明 Halo 的暴露方式
```

2022-08-09 14:20 UTC, ruibaby commented on docs/getting-started/install/other/kubernetes.md
> +配置证书，提供 https 访问 halo 服务
```suggestion
配置证书，提供 https 访问 Halo 服务
```

2022-08-09 14:21 UTC, ruibaby commented on docs/getting-started/install/other/kubernetes.md
> +## 配置ingress,提供外部访问方式
```suggestion
## 配置 Ingress，提供外部访问方式
```

2022-08-09 14:21 UTC, ruibaby commented on docs/getting-started/install/other/kubernetes.md
> +    - host: devopsman.cn
需要提示读者修改此 host

2022-08-09 14:21 UTC, ruibaby commented on docs/getting-started/install/other/kubernetes.md
> +        - devopsman.cn
同上

2022-08-09 14:21 UTC, ruibaby commented on docs/getting-started/install/other/kubernetes.md
> +## 最后验证halo服务
```suggestion
## 最后验证 Halo 服务
```

2022-08-09 14:23 UTC, ruibaby commented on pnpm-lock.yaml
> -lockfileVersion: 5.3
非必要修改，一般情况下不建议改动 pnpm-lock.yaml。此改动应该是你本地使用了其他镜像导致的。

2022-08-09 14:25 UTC, ruibaby commented
/cc @halo-dev/sig-docs

2022-08-09 14:27 UTC, ruibaby requested changes

2022-08-09 14:27 UTC, ruibaby commented on docs/getting-started/install/other/kubernetes.md
> +![halo-test](/img/halo-test.jpg)
建议使用代码块代替图片。

2022-08-09 14:27 UTC, ruibaby commented on docs/getting-started/install/other/kubernetes.md
> +![halo-kubernetes](/img/halo-kubernetes.jpg)
建议使用代码块代替图片。

2022-08-11 00:53 UTC, marionxue commented on docs/getting-started/install/other/kubernetes.md
> +![halo-test](/img/halo-test.jpg)
Ok

2022-08-11 00:53 UTC, marionxue commented on docs/getting-started/install/other/kubernetes.md
> +    - host: devopsman.cn
ok

2022-08-11 00:53 UTC, marionxue commented on docs/getting-started/install/other/kubernetes.md
> +        - devopsman.cn
ok

2022-08-11 00:54 UTC, marionxue commented on docs/getting-started/install/other/kubernetes.md
> +![halo-kubernetes](/img/halo-kubernetes.jpg)
ok

2022-08-11 06:22 UTC, JohnNiang commented on versioned_docs/version-1.5.4/getting-started/install/other/kubernetes.md
> +## 配置证书
如果能够提供两种配置证书的方式就更好了 : )

1. 已有证书的配置
2. Let's Encrypt 免费证书配置（可参考 [cert-manager](https://cert-manager.io/)）

2022-08-11 08:36 UTC, marionxue commented on versioned_docs/version-1.5.4/getting-started/install/other/kubernetes.md
> +## 配置证书
文章已提供已有证书配置，Let's Encrypt 免费证书配置 暂没计划

2022-08-14 14:06 UTC, JohnNiang commented on versioned_docs/version-1.5.4/getting-started/install/other/kubernetes.md
> +## 配置证书
当前文档已经非常棒了！关于免费证书配置，可以后期让社区用户继续完善。

近期我会抽空手动测试一下 Kubernetes 环境中部署 Halo 的文档。

2022-09-13 06:17 UTC, JohnNiang commented
非常抱歉最近没有时间测试 Kubernetes 部署。目前我们正在紧张地开发 Halo 2.0。

建议当前 PR 保持打开的状态，继续等待社区的反馈。

/reopen

2023-06-29 08:17 UTC, JohnNiang commented
Hi @marionxue , 我们已经提供了 [Helm Charts](https://github.com/halo-sigs/charts)，并提供了对应的部署文档，请参考 <https://github.com/halo-dev/docs/pull/233>。相对于手动编写 Manifest 文件，不容易出错，更易维护，更简单。

再次感谢 @marionxue 的参与！我们将关闭当前 PR。如果有任何问题可随时重新打开。

2023-06-29 08:17 UTC, closed without merging